-- A shared vocabulary for what small businesses here actually sell.
--
-- Two problems, one table. Onboarding a shop means typing hundreds of products
-- by hand, which is the real reason somebody gives up in the first ten minutes.
-- And the same item entered as "Milk 1L", "Maziwa", "maziwa lita moja" and
-- "MILK 1 LITRE" cannot be compared across shops, or reported on honestly even
-- within one.
--
-- Entries are deliberately generic product plus pack size, never brand. Brands
-- multiply this list many times over and can arrive later as a second field.
-- The aliases carry the Swahili, the Sheng and the spellings people type.
--
-- `business_types` is what keeps this usable. A pharmacy must not be offered
-- maziwa and a hardware must not be offered sukuma wiki, so suggestions are
-- ranked by the shop's own trade first. An entry can belong to several: a duka
-- and a bar both sell cigarettes.
--
-- `kind` separates goods from services. A kinyozi sells haircuts, which have a
-- price and no stock level. This is a label on the vocabulary only; it does not
-- reintroduce the services branching that was deliberately stripped in August.

CREATE TABLE IF NOT EXISTS public.canonical_products (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL UNIQUE,
  category TEXT NOT NULL,
  pack_size TEXT,
  kind TEXT NOT NULL DEFAULT 'goods' CHECK (kind IN ('goods', 'service')),
  business_types TEXT[] NOT NULL DEFAULT '{}',
  aliases TEXT[] NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Reference data, not shop data: every signed-in user reads the same rows and
-- nobody writes them from a client. Growing the list is a migration or a
-- service-role job, so one shop can never reshape the vocabulary for everyone.
ALTER TABLE public.canonical_products ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone signed in can read the catalogue" ON public.canonical_products;
CREATE POLICY "Anyone signed in can read the catalogue"
  ON public.canonical_products FOR SELECT
  TO authenticated
  USING (true);

-- pg_trgm is for matching names already typed, in bulk, later. Live suggestions
-- are matched on the client so they keep working on a bad connection.
CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA extensions;
CREATE INDEX IF NOT EXISTS canonical_products_name_trgm
  ON public.canonical_products USING gin (name extensions.gin_trgm_ops);
CREATE INDEX IF NOT EXISTS canonical_products_business_types_idx
  ON public.canonical_products USING gin (business_types);

-- The link from a shop's own product to the shared vocabulary.
--
-- ON DELETE SET NULL, never CASCADE: retiring a catalogue entry must not delete
-- somebody's product. Losing the link is recoverable, losing the stock record
-- is not.
ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS canonical_id UUID REFERENCES public.canonical_products(id) ON DELETE SET NULL;

-- How the link was made, which decides how far it can be trusted. 'chosen'
-- means a person tapped the suggestion. 'matched' means we guessed. Only
-- 'chosen' should ever be treated as ground truth.
ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS canonical_source TEXT
  CHECK (canonical_source IS NULL OR canonical_source IN ('chosen', 'matched'));

CREATE INDEX IF NOT EXISTS products_canonical_id_idx ON public.products (canonical_id);

INSERT INTO public.canonical_products (name, category, pack_size, kind, business_types, aliases) VALUES
  ('Maize Flour 1kg', 'Staples', '1kg', 'goods', ARRAY['duka', 'grains_store', 'mini_supermarket'], ARRAY['unga', 'unga wa mahindi', 'ugali flour', 'maize meal']),
  ('Maize Flour 2kg', 'Staples', '2kg', 'goods', ARRAY['duka', 'grains_store', 'mini_supermarket'], ARRAY['unga 2kg', 'unga wa mahindi 2kg']),
  ('Wheat Flour 1kg', 'Staples', '1kg', 'goods', ARRAY['duka', 'grains_store', 'mini_supermarket'], ARRAY['unga wa ngano', 'wheat flour', 'ngano']),
  ('Wheat Flour 2kg', 'Staples', '2kg', 'goods', ARRAY['duka', 'grains_store', 'mini_supermarket'], ARRAY['unga wa ngano 2kg', 'ngano 2kg']),
  ('Rice 1kg', 'Staples', '1kg', 'goods', ARRAY['duka', 'grains_store', 'mini_supermarket'], ARRAY['mchele', 'pishori', 'rice']),
  ('Rice 2kg', 'Staples', '2kg', 'goods', ARRAY['duka', 'grains_store', 'mini_supermarket'], ARRAY['mchele 2kg', 'pishori 2kg']),
  ('Rice 5kg', 'Staples', '5kg', 'goods', ARRAY['duka', 'grains_store', 'mini_supermarket'], ARRAY['mchele 5kg', 'pishori 5kg']),
  ('Sugar 500g', 'Staples', '500g', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['sukari 500g', 'sukari nusu kilo']),
  ('Sugar 1kg', 'Staples', '1kg', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['sukari', 'sugar', 'sukari kilo moja']),
  ('Sugar 2kg', 'Staples', '2kg', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['sukari 2kg', 'sugar 2kg']),
  ('Salt 500g', 'Staples', '500g', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['chumvi', 'salt']),
  ('Cooking Salt 1kg', 'Staples', '1kg', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['chumvi 1kg', 'salt 1kg']),
  ('Cooking Oil 500ml', 'Staples', '500ml', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['mafuta 500ml', 'salad 500ml']),
  ('Cooking Oil 1L', 'Staples', '1L', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['mafuta', 'mafuta ya kupika', 'salad', 'cooking oil']),
  ('Cooking Oil 2L', 'Staples', '2L', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['mafuta 2l', 'salad 2l', 'mafuta lita mbili']),
  ('Cooking Oil 3L', 'Staples', '3L', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['mafuta 3l', 'salad 3l']),
  ('Cooking Fat 500g', 'Staples', '500g', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['kimbo', 'cooking fat', 'mafuta ngumu']),
  ('Beans 1kg', 'Staples', '1kg', 'goods', ARRAY['duka', 'grains_store', 'mini_supermarket'], ARRAY['maharagwe', 'maharage', 'beans', 'nyayo beans']),
  ('Green Grams 1kg', 'Staples', '1kg', 'goods', ARRAY['duka', 'grains_store', 'mini_supermarket'], ARRAY['ndengu', 'green grams', 'pojo']),
  ('Lentils 1kg', 'Staples', '1kg', 'goods', ARRAY['duka', 'grains_store', 'mini_supermarket'], ARRAY['kamande', 'lentils']),
  ('Spaghetti 500g', 'Staples', '500g', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['tambi', 'spaghetti']),
  ('Macaroni 500g', 'Staples', '500g', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['macaroni', 'pasta']),
  ('Fresh Milk 500ml', 'Dairy', '500ml', 'goods', ARRAY['duka', 'mini_supermarket', 'poultry_dairy'], ARRAY['maziwa 500ml', 'milk half litre']),
  ('Fresh Milk 1L', 'Dairy', '1L', 'goods', ARRAY['duka', 'mini_supermarket', 'poultry_dairy'], ARRAY['maziwa', 'maziwa lita moja', 'milk 1 litre']),
  ('Long Life Milk 500ml', 'Dairy', '500ml', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['uht milk 500ml', 'maziwa ya ndani 500ml']),
  ('Long Life Milk 1L', 'Dairy', '1L', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['uht milk', 'long life milk', 'maziwa ya ndani']),
  ('Fermented Milk 500ml', 'Dairy', '500ml', 'goods', ARRAY['duka', 'mini_supermarket', 'poultry_dairy'], ARRAY['mala', 'maziwa lala', 'fermented milk']),
  ('Yoghurt 250ml', 'Dairy', '250ml', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['yoghurt', 'yogurt']),
  ('Yoghurt 500ml', 'Dairy', '500ml', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['yoghurt 500ml']),
  ('Margarine 250g', 'Dairy', '250g', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['blueband', 'blue band', 'margarine', 'siagi']),
  ('Margarine 500g', 'Dairy', '500g', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['blueband 500g', 'margarine 500g']),
  ('Milk Powder 250g', 'Dairy', '250g', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['milk powder', 'maziwa ya unga']),
  ('Bread 400g', 'Bakery', '400g', 'goods', ARRAY['bakery', 'duka', 'mini_supermarket'], ARRAY['mkate', 'bread', 'half loaf']),
  ('Bread 800g', 'Bakery', '800g', 'goods', ARRAY['bakery', 'duka', 'mini_supermarket'], ARRAY['mkate mkubwa', 'full loaf']),
  ('Brown Bread 400g', 'Bakery', '400g', 'goods', ARRAY['bakery', 'duka', 'mini_supermarket'], ARRAY['brown bread', 'mkate wa brown']),
  ('Mandazi', 'Bakery', 'piece', 'goods', ARRAY['bakery', 'restaurant', 'street_vendor'], ARRAY['mandazi', 'maandazi']),
  ('Chapati', 'Bakery', 'piece', 'goods', ARRAY['bakery', 'restaurant', 'street_vendor'], ARRAY['chapati', 'chapo']),
  ('Buns', 'Bakery', 'piece', 'goods', ARRAY['bakery', 'duka'], ARRAY['buns', 'bun']),
  ('Scones', 'Bakery', 'piece', 'goods', ARRAY['bakery'], ARRAY['scones', 'skonzi']),
  ('Doughnuts', 'Bakery', 'piece', 'goods', ARRAY['bakery'], ARRAY['doughnut', 'donut']),
  ('Queen Cakes', 'Bakery', 'piece', 'goods', ARRAY['bakery'], ARRAY['queen cakes', 'cup cakes']),
  ('Birthday Cake', 'Bakery', 'piece', 'goods', ARRAY['bakery'], ARRAY['birthday cake', 'keki ya siku ya kuzaliwa']),
  ('Cake Slice', 'Bakery', 'piece', 'goods', ARRAY['bakery', 'restaurant'], ARRAY['cake slice', 'keki']),
  ('Cookies', 'Bakery', 'pack', 'goods', ARRAY['bakery', 'duka'], ARRAY['cookies']),
  ('Soda 300ml', 'Drinks', '300ml', 'goods', ARRAY['bar_liquor', 'duka', 'mini_supermarket', 'restaurant'], ARRAY['soda', 'soda ndogo', 'coke 300ml']),
  ('Soda 500ml', 'Drinks', '500ml', 'goods', ARRAY['bar_liquor', 'duka', 'mini_supermarket', 'restaurant'], ARRAY['soda 500ml', 'soda plastic']),
  ('Soda 1L', 'Drinks', '1L', 'goods', ARRAY['duka', 'mini_supermarket', 'restaurant'], ARRAY['soda 1l', 'coke 1 litre']),
  ('Soda 2L', 'Drinks', '2L', 'goods', ARRAY['duka', 'mini_supermarket', 'restaurant'], ARRAY['soda 2l', 'soda kubwa']),
  ('Bottled Water 500ml', 'Drinks', '500ml', 'goods', ARRAY['duka', 'mini_supermarket', 'restaurant', 'water_refill'], ARRAY['maji', 'maji 500ml', 'water']),
  ('Bottled Water 1L', 'Drinks', '1L', 'goods', ARRAY['duka', 'mini_supermarket', 'water_refill'], ARRAY['maji 1l', 'water 1 litre']),
  ('Bottled Water 5L', 'Drinks', '5L', 'goods', ARRAY['duka', 'mini_supermarket', 'water_refill'], ARRAY['maji 5l', 'water 5 litre']),
  ('Bottled Water 20L', 'Drinks', '20L', 'goods', ARRAY['duka', 'mini_supermarket', 'water_refill'], ARRAY['maji 20l', 'dumu ya maji']),
  ('Juice 250ml', 'Drinks', '250ml', 'goods', ARRAY['duka', 'mini_supermarket', 'restaurant'], ARRAY['juisi', 'juice']),
  ('Juice 500ml', 'Drinks', '500ml', 'goods', ARRAY['duka', 'mini_supermarket', 'restaurant'], ARRAY['juisi 500ml']),
  ('Juice 1L', 'Drinks', '1L', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['juisi 1l', 'juice 1 litre']),
  ('Tea Leaves 100g', 'Drinks', '100g', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['majani chai', 'majani ya chai', 'tea leaves']),
  ('Tea Leaves 250g', 'Drinks', '250g', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['majani chai 250g']),
  ('Tea Leaves 500g', 'Drinks', '500g', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['majani chai 500g']),
  ('Coffee 100g', 'Drinks', '100g', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['kahawa', 'coffee']),
  ('Drinking Chocolate 200g', 'Drinks', '200g', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['drinking chocolate', 'cocoa', 'milo']),
  ('Energy Drink 300ml', 'Drinks', '300ml', 'goods', ARRAY['bar_liquor', 'duka', 'mini_supermarket'], ARRAY['energy drink', 'power play']),
  ('Beer 500ml', 'Alcohol', '500ml', 'goods', ARRAY['bar_liquor', 'restaurant'], ARRAY['bia', 'beer', 'tusker', 'pilsner']),
  ('Beer 330ml', 'Alcohol', '330ml', 'goods', ARRAY['bar_liquor'], ARRAY['bia ndogo', 'beer can']),
  ('Cider 500ml', 'Alcohol', '500ml', 'goods', ARRAY['bar_liquor'], ARRAY['cider', 'snapp', 'savanna']),
  ('Wine 750ml', 'Alcohol', '750ml', 'goods', ARRAY['bar_liquor'], ARRAY['mvinyo', 'wine', 'red wine', 'white wine']),
  ('Wine 375ml', 'Alcohol', '375ml', 'goods', ARRAY['bar_liquor'], ARRAY['wine 375ml', 'half wine']),
  ('Whisky 250ml', 'Alcohol', '250ml', 'goods', ARRAY['bar_liquor'], ARRAY['whisky 250ml', 'quarter whisky']),
  ('Whisky 750ml', 'Alcohol', '750ml', 'goods', ARRAY['bar_liquor'], ARRAY['whisky', 'whiskey']),
  ('Vodka 250ml', 'Alcohol', '250ml', 'goods', ARRAY['bar_liquor'], ARRAY['vodka 250ml', 'quarter vodka']),
  ('Vodka 750ml', 'Alcohol', '750ml', 'goods', ARRAY['bar_liquor'], ARRAY['vodka']),
  ('Gin 750ml', 'Alcohol', '750ml', 'goods', ARRAY['bar_liquor'], ARRAY['gin']),
  ('Brandy 750ml', 'Alcohol', '750ml', 'goods', ARRAY['bar_liquor'], ARRAY['brandy']),
  ('Rum 750ml', 'Alcohol', '750ml', 'goods', ARRAY['bar_liquor'], ARRAY['rum']),
  ('Spirits 250ml', 'Alcohol', '250ml', 'goods', ARRAY['bar_liquor'], ARRAY['spirit 250ml', 'quarter', 'kasiki']),
  ('Keg Beer', 'Alcohol', 'glass', 'goods', ARRAY['bar_liquor'], ARRAY['keg', 'senator', 'keg beer']),
  ('Shot', 'Alcohol', 'service', 'service', ARRAY['bar_liquor'], ARRAY['shot', 'tot']),
  ('Bar Soap 800g', 'Household', '800g', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['sabuni', 'sabuni ya kufulia', 'bar soap']),
  ('Bar Soap 1kg', 'Household', '1kg', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['sabuni 1kg']),
  ('Washing Powder 500g', 'Household', '500g', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['omo', 'sabuni ya unga', 'washing powder']),
  ('Washing Powder 1kg', 'Household', '1kg', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['omo 1kg']),
  ('Dishwashing Liquid 500ml', 'Household', '500ml', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['sabuni ya vyombo', 'dishwashing liquid']),
  ('Dishwashing Bar', 'Household', 'piece', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['sabuni ya vyombo bar']),
  ('Bleach 500ml', 'Household', '500ml', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['jik', 'bleach']),
  ('Bleach 750ml', 'Household', '750ml', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['jik 750ml']),
  ('Steel Wool', 'Household', 'piece', 'goods', ARRAY['duka', 'household_goods', 'mini_supermarket'], ARRAY['steel wool', 'scourer']),
  ('Matches', 'Household', 'box', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['kiberiti', 'matches']),
  ('Candles', 'Household', 'piece', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['mshumaa', 'mishumaa', 'candle']),
  ('Toilet Paper Roll', 'Household', 'roll', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['karatasi ya choo', 'tissue', 'toilet paper']),
  ('Toilet Paper 4 Pack', 'Household', '4 pack', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['tissue 4']),
  ('Toilet Paper 10 Pack', 'Household', '10 pack', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['tissue 10']),
  ('Tissue Box', 'Household', 'box', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['tissue box', 'serviette']),
  ('Paraffin 1L', 'Household', '1L', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['mafuta ya taa', 'paraffin', 'kerosene']),
  ('Charcoal 1kg', 'Household', '1kg', 'goods', ARRAY['duka', 'mini_supermarket', 'street_vendor'], ARRAY['makaa', 'charcoal']),
  ('Charcoal Sack', 'Household', 'sack', 'goods', ARRAY['duka', 'street_vendor'], ARRAY['gunia la makaa', 'makaa gunia']),
  ('Insecticide Spray', 'Household', 'can', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['doom', 'insecticide', 'dawa ya wadudu']),
  ('Toothpaste 50ml', 'Personal care', '50ml', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['dawa ya meno 50ml']),
  ('Toothpaste 100ml', 'Personal care', '100ml', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['dawa ya meno', 'colgate', 'toothpaste']),
  ('Toothbrush', 'Personal care', 'piece', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['mswaki', 'toothbrush']),
  ('Petroleum Jelly 100g', 'Personal care', '100g', 'goods', ARRAY['beauty_shop', 'duka', 'mini_supermarket'], ARRAY['vaseline', 'petroleum jelly']),
  ('Petroleum Jelly 250g', 'Personal care', '250g', 'goods', ARRAY['beauty_shop', 'duka', 'mini_supermarket'], ARRAY['vaseline 250g']),
  ('Body Lotion 200ml', 'Personal care', '200ml', 'goods', ARRAY['beauty_shop', 'duka', 'mini_supermarket'], ARRAY['lotion', 'mafuta ya mwili']),
  ('Body Lotion 400ml', 'Personal care', '400ml', 'goods', ARRAY['beauty_shop', 'duka', 'mini_supermarket'], ARRAY['lotion 400ml']),
  ('Bathing Soap', 'Personal care', 'piece', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['sabuni ya kuoga', 'geisha']),
  ('Shampoo 200ml', 'Personal care', '200ml', 'goods', ARRAY['beauty_shop', 'duka', 'mini_supermarket', 'salon'], ARRAY['shampoo', 'shampu']),
  ('Sanitary Pads', 'Personal care', 'pack', 'goods', ARRAY['duka', 'mini_supermarket', 'pharmacy'], ARRAY['pads', 'taulo za kike']),
  ('Razor Blades', 'Personal care', 'pack', 'goods', ARRAY['duka', 'kinyozi', 'mini_supermarket'], ARRAY['wembe', 'razor']),
  ('Roll On Deodorant', 'Personal care', 'piece', 'goods', ARRAY['beauty_shop', 'duka', 'mini_supermarket'], ARRAY['roll on', 'deodorant']),
  ('Biscuits Small', 'Snacks', 'piece', 'goods', ARRAY['duka', 'mini_supermarket', 'street_vendor'], ARRAY['biskuti', 'biscuits']),
  ('Biscuits Family Pack', 'Snacks', 'pack', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['biskuti kubwa']),
  ('Crisps 50g', 'Snacks', '50g', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['crisps', 'chipsi', 'potato crisps']),
  ('Sweets', 'Snacks', 'piece', 'goods', ARRAY['duka', 'mini_supermarket', 'street_vendor'], ARRAY['peremende', 'sweets']),
  ('Chewing Gum', 'Snacks', 'piece', 'goods', ARRAY['duka', 'mini_supermarket', 'street_vendor'], ARRAY['gum', 'chewing gum']),
  ('Groundnuts 100g', 'Snacks', '100g', 'goods', ARRAY['duka', 'mini_supermarket', 'street_vendor'], ARRAY['njugu', 'karanga', 'peanuts']),
  ('Popcorn', 'Snacks', 'pack', 'goods', ARRAY['duka', 'mini_supermarket', 'street_vendor'], ARRAY['popcorn', 'bisi']),
  ('Tomato Paste 50g', 'Cooking', '50g', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['tomato paste']),
  ('Tomato Paste 400g', 'Cooking', '400g', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['tomato paste 400g']),
  ('Tomato Sauce 400ml', 'Cooking', '400ml', 'goods', ARRAY['duka', 'mini_supermarket', 'restaurant'], ARRAY['tomato sauce', 'ketchup']),
  ('Curry Powder 100g', 'Cooking', '100g', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['bizari', 'curry powder']),
  ('Stock Cubes', 'Cooking', 'piece', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['royco', 'knorr', 'supu']),
  ('Black Pepper 50g', 'Cooking', '50g', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['pilipili manga', 'black pepper']),
  ('Chilli Powder 50g', 'Cooking', '50g', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['pilipili', 'chilli']),
  ('Vinegar 500ml', 'Cooking', '500ml', 'goods', ARRAY['duka', 'mini_supermarket'], ARRAY['siki', 'vinegar']),
  ('Baking Powder 100g', 'Cooking', '100g', 'goods', ARRAY['bakery', 'duka', 'mini_supermarket'], ARRAY['baking powder']),
  ('Yeast 50g', 'Cooking', '50g', 'goods', ARRAY['bakery', 'duka', 'mini_supermarket'], ARRAY['hamira', 'yeast']),
  ('Baby Diapers Small Pack', 'Baby', 'pack', 'goods', ARRAY['duka', 'mini_supermarket', 'pharmacy'], ARRAY['nepi', 'pampers', 'diapers']),
  ('Baby Wipes', 'Baby', 'pack', 'goods', ARRAY['duka', 'mini_supermarket', 'pharmacy'], ARRAY['baby wipes', 'wipes']),
  ('Baby Cereal 400g', 'Baby', '400g', 'goods', ARRAY['duka', 'mini_supermarket', 'pharmacy'], ARRAY['cerelac', 'uji wa mtoto']),
  ('Eggs Single', 'Other', 'piece', 'goods', ARRAY['duka', 'mini_supermarket', 'poultry_dairy', 'street_vendor'], ARRAY['yai', 'egg']),
  ('Eggs Tray', 'Other', 'tray', 'goods', ARRAY['duka', 'mini_supermarket', 'poultry_dairy'], ARRAY['mayai', 'tray ya mayai', 'kreti ya mayai']),
  ('Airtime', 'Other', 'voucher', 'goods', ARRAY['duka', 'mini_supermarket', 'mpesa_agent'], ARRAY['airtime', 'salio', 'scratch card']),
  ('Cigarettes Single', 'Other', 'piece', 'goods', ARRAY['bar_liquor', 'duka', 'mini_supermarket'], ARRAY['sigara', 'fegi']),
  ('Cigarettes Packet', 'Other', 'packet', 'goods', ARRAY['bar_liquor', 'duka', 'mini_supermarket'], ARRAY['sigara packet']),
  ('Batteries AA', 'Other', 'pack', 'goods', ARRAY['duka', 'electronics', 'mini_supermarket'], ARRAY['betri', 'batteries']),
  ('Batteries D', 'Other', 'pack', 'goods', ARRAY['duka', 'electronics', 'mini_supermarket'], ARRAY['betri kubwa', 'torch battery']),
  ('Sukuma Wiki', 'Vegetables', 'bunch', 'goods', ARRAY['grocery_kiosk', 'street_vendor'], ARRAY['sukuma', 'sukuma wiki', 'kales']),
  ('Spinach', 'Vegetables', 'bunch', 'goods', ARRAY['grocery_kiosk', 'street_vendor'], ARRAY['spinach', 'mchicha']),
  ('Cabbage', 'Vegetables', 'piece', 'goods', ARRAY['grocery_kiosk', 'street_vendor'], ARRAY['kabeji', 'cabbage']),
  ('Tomatoes', 'Vegetables', 'kg', 'goods', ARRAY['grocery_kiosk', 'street_vendor'], ARRAY['nyanya', 'tomatoes']),
  ('Onions', 'Vegetables', 'kg', 'goods', ARRAY['grocery_kiosk', 'street_vendor'], ARRAY['vitunguu', 'onions']),
  ('Potatoes', 'Vegetables', 'kg', 'goods', ARRAY['grocery_kiosk', 'street_vendor'], ARRAY['viazi', 'potatoes', 'waru']),
  ('Carrots', 'Vegetables', 'kg', 'goods', ARRAY['grocery_kiosk', 'street_vendor'], ARRAY['karoti', 'carrots']),
  ('Dhania', 'Vegetables', 'bunch', 'goods', ARRAY['grocery_kiosk', 'street_vendor'], ARRAY['dhania', 'coriander']),
  ('Capsicum', 'Vegetables', 'piece', 'goods', ARRAY['grocery_kiosk', 'street_vendor'], ARRAY['pilipili hoho', 'capsicum', 'hoho']),
  ('Garlic', 'Vegetables', 'piece', 'goods', ARRAY['grocery_kiosk', 'street_vendor'], ARRAY['kitunguu saumu', 'garlic']),
  ('Ginger', 'Vegetables', 'kg', 'goods', ARRAY['grocery_kiosk', 'street_vendor'], ARRAY['tangawizi', 'ginger']),
  ('Managu', 'Vegetables', 'bunch', 'goods', ARRAY['grocery_kiosk', 'street_vendor'], ARRAY['managu', 'african nightshade']),
  ('Terere', 'Vegetables', 'bunch', 'goods', ARRAY['grocery_kiosk', 'street_vendor'], ARRAY['terere', 'amaranth']),
  ('Kunde', 'Vegetables', 'bunch', 'goods', ARRAY['grocery_kiosk', 'street_vendor'], ARRAY['kunde', 'cowpea leaves']),
  ('Pumpkin', 'Vegetables', 'piece', 'goods', ARRAY['grocery_kiosk', 'street_vendor'], ARRAY['malenge', 'pumpkin']),
  ('Butternut', 'Vegetables', 'piece', 'goods', ARRAY['grocery_kiosk', 'street_vendor'], ARRAY['butternut']),
  ('Cucumber', 'Vegetables', 'piece', 'goods', ARRAY['grocery_kiosk', 'street_vendor'], ARRAY['tango', 'cucumber']),
  ('Courgette', 'Vegetables', 'kg', 'goods', ARRAY['grocery_kiosk', 'street_vendor'], ARRAY['courgette', 'zucchini']),
  ('French Beans', 'Vegetables', 'kg', 'goods', ARRAY['grocery_kiosk', 'street_vendor'], ARRAY['french beans', 'mishiri']),
  ('Sweet Potatoes', 'Vegetables', 'kg', 'goods', ARRAY['grocery_kiosk', 'street_vendor'], ARRAY['viazi vitamu', 'sweet potato']),
  ('Arrow Roots', 'Vegetables', 'kg', 'goods', ARRAY['grocery_kiosk', 'street_vendor'], ARRAY['nduma', 'arrow roots']),
  ('Cassava', 'Vegetables', 'kg', 'goods', ARRAY['grocery_kiosk', 'street_vendor'], ARRAY['muhogo', 'cassava']),
  ('Green Maize', 'Vegetables', 'piece', 'goods', ARRAY['grocery_kiosk', 'nyama_choma', 'street_vendor'], ARRAY['mahindi', 'green maize']),
  ('Cooking Bananas', 'Vegetables', 'bunch', 'goods', ARRAY['grocery_kiosk', 'street_vendor'], ARRAY['matoke', 'ndizi za kupika']),
  ('Bananas', 'Fruit', 'piece', 'goods', ARRAY['fruit_kiosk', 'grocery_kiosk', 'street_vendor'], ARRAY['ndizi', 'bananas']),
  ('Mangoes', 'Fruit', 'piece', 'goods', ARRAY['fruit_kiosk', 'grocery_kiosk', 'street_vendor'], ARRAY['maembe', 'mango']),
  ('Oranges', 'Fruit', 'piece', 'goods', ARRAY['fruit_kiosk', 'grocery_kiosk', 'street_vendor'], ARRAY['machungwa', 'oranges']),
  ('Pineapple', 'Fruit', 'piece', 'goods', ARRAY['fruit_kiosk', 'grocery_kiosk', 'street_vendor'], ARRAY['nanasi', 'pineapple']),
  ('Watermelon', 'Fruit', 'piece', 'goods', ARRAY['fruit_kiosk', 'grocery_kiosk', 'street_vendor'], ARRAY['tikiti maji', 'watermelon']),
  ('Apples', 'Fruit', 'piece', 'goods', ARRAY['fruit_kiosk', 'grocery_kiosk', 'street_vendor'], ARRAY['tufaha', 'apples']),
  ('Passion Fruit', 'Fruit', 'kg', 'goods', ARRAY['fruit_kiosk', 'grocery_kiosk', 'street_vendor'], ARRAY['passion', 'matunda ya passion']),
  ('Avocado', 'Fruit', 'piece', 'goods', ARRAY['fruit_kiosk', 'grocery_kiosk', 'street_vendor'], ARRAY['parachichi', 'avocado']),
  ('Pawpaw', 'Fruit', 'piece', 'goods', ARRAY['fruit_kiosk', 'grocery_kiosk', 'street_vendor'], ARRAY['papai', 'pawpaw', 'papaya']),
  ('Lemons', 'Fruit', 'piece', 'goods', ARRAY['fruit_kiosk', 'grocery_kiosk', 'street_vendor'], ARRAY['ndimu', 'lemon']),
  ('Tree Tomato', 'Fruit', 'piece', 'goods', ARRAY['fruit_kiosk', 'grocery_kiosk', 'street_vendor'], ARRAY['matunda ya damu', 'tree tomato']),
  ('Guava', 'Fruit', 'piece', 'goods', ARRAY['fruit_kiosk', 'grocery_kiosk', 'street_vendor'], ARRAY['mapera', 'guava']),
  ('Grapes', 'Fruit', 'kg', 'goods', ARRAY['fruit_kiosk'], ARRAY['zabibu', 'grapes']),
  ('Plums', 'Fruit', 'kg', 'goods', ARRAY['fruit_kiosk'], ARRAY['plums']),
  ('Beef', 'Meat', 'kg', 'goods', ARRAY['butchery'], ARRAY['nyama ya ngombe', 'beef']),
  ('Goat Meat', 'Meat', 'kg', 'goods', ARRAY['butchery', 'nyama_choma'], ARRAY['nyama ya mbuzi', 'goat meat', 'mbuzi']),
  ('Mutton', 'Meat', 'kg', 'goods', ARRAY['butchery'], ARRAY['nyama ya kondoo', 'mutton']),
  ('Pork', 'Meat', 'kg', 'goods', ARRAY['butchery', 'nyama_choma'], ARRAY['nyama ya nguruwe', 'pork']),
  ('Chicken Whole', 'Meat', 'piece', 'goods', ARRAY['butchery', 'poultry_dairy'], ARRAY['kuku mzima', 'whole chicken']),
  ('Chicken Pieces', 'Meat', 'kg', 'goods', ARRAY['butchery'], ARRAY['kuku', 'chicken pieces']),
  ('Minced Meat', 'Meat', 'kg', 'goods', ARRAY['butchery'], ARRAY['nyama ya kusaga', 'minced meat']),
  ('Liver', 'Meat', 'kg', 'goods', ARRAY['butchery'], ARRAY['maini', 'liver']),
  ('Matumbo', 'Meat', 'kg', 'goods', ARRAY['butchery', 'nyama_choma'], ARRAY['matumbo', 'tripe']),
  ('Bones', 'Meat', 'kg', 'goods', ARRAY['butchery'], ARRAY['mifupa', 'bones']),
  ('Mutura', 'Meat', 'piece', 'goods', ARRAY['nyama_choma', 'street_vendor'], ARRAY['mutura']),
  ('Fish', 'Meat', 'piece', 'goods', ARRAY['butchery', 'restaurant'], ARRAY['samaki', 'fish', 'tilapia']),
  ('Smokies', 'Street food', 'piece', 'goods', ARRAY['nyama_choma', 'street_vendor'], ARRAY['smokie', 'smokies']),
  ('Sausages', 'Street food', 'piece', 'goods', ARRAY['nyama_choma', 'street_vendor'], ARRAY['soseji', 'sausage']),
  ('Boiled Eggs', 'Street food', 'piece', 'goods', ARRAY['nyama_choma', 'street_vendor'], ARRAY['mayai ya kuchemsha', 'boiled egg']),
  ('Roast Maize', 'Street food', 'piece', 'goods', ARRAY['nyama_choma', 'street_vendor'], ARRAY['mahindi ya kuchoma', 'roast maize']),
  ('Kachumbari', 'Street food', 'portion', 'goods', ARRAY['nyama_choma', 'restaurant', 'street_vendor'], ARRAY['kachumbari', 'salad']),
  ('Nyama Choma', 'Street food', 'kg', 'goods', ARRAY['nyama_choma', 'restaurant'], ARRAY['nyama choma', 'roast meat']),
  ('Roast Chicken', 'Street food', 'piece', 'goods', ARRAY['nyama_choma', 'restaurant'], ARRAY['kuku choma', 'roast chicken']),
  ('Samosa', 'Street food', 'piece', 'goods', ARRAY['nyama_choma', 'restaurant', 'street_vendor'], ARRAY['sambusa', 'samosa']),
  ('Ugali', 'Meals', 'portion', 'goods', ARRAY['restaurant'], ARRAY['ugali', 'sima']),
  ('Rice Portion', 'Meals', 'portion', 'goods', ARRAY['restaurant'], ARRAY['wali', 'rice']),
  ('Pilau', 'Meals', 'portion', 'goods', ARRAY['restaurant'], ARRAY['pilau']),
  ('Githeri', 'Meals', 'portion', 'goods', ARRAY['restaurant'], ARRAY['githeri']),
  ('Beans Stew', 'Meals', 'portion', 'goods', ARRAY['restaurant'], ARRAY['maharagwe', 'beans stew']),
  ('Beef Stew', 'Meals', 'portion', 'goods', ARRAY['restaurant'], ARRAY['nyama ya kupika', 'beef stew']),
  ('Chicken Stew', 'Meals', 'portion', 'goods', ARRAY['restaurant'], ARRAY['kuku stew', 'chicken stew']),
  ('Chips', 'Meals', 'portion', 'goods', ARRAY['restaurant', 'street_vendor'], ARRAY['chipsi', 'chips', 'fries']),
  ('Matoke', 'Meals', 'portion', 'goods', ARRAY['restaurant'], ARRAY['matoke']),
  ('Sukuma Portion', 'Meals', 'portion', 'goods', ARRAY['restaurant'], ARRAY['sukuma', 'greens']),
  ('Cabbage Portion', 'Meals', 'portion', 'goods', ARRAY['restaurant'], ARRAY['kabeji']),
  ('Tea Cup', 'Meals', 'cup', 'goods', ARRAY['restaurant', 'street_vendor'], ARRAY['chai', 'tea']),
  ('Coffee Cup', 'Meals', 'cup', 'goods', ARRAY['restaurant'], ARRAY['kahawa', 'coffee']),
  ('Breakfast', 'Meals', 'plate', 'goods', ARRAY['restaurant'], ARRAY['breakfast', 'kifungua kinywa']),
  ('Lunch', 'Meals', 'plate', 'goods', ARRAY['restaurant'], ARRAY['lunch', 'chakula cha mchana']),
  ('Paracetamol Tablets', 'Medicine', 'pack', 'goods', ARRAY['pharmacy'], ARRAY['panadol', 'paracetamol', 'dawa ya kichwa']),
  ('Ibuprofen Tablets', 'Medicine', 'pack', 'goods', ARRAY['pharmacy'], ARRAY['ibuprofen', 'brufen']),
  ('Aspirin Tablets', 'Medicine', 'pack', 'goods', ARRAY['pharmacy'], ARRAY['aspirin']),
  ('Antimalarial Tablets', 'Medicine', 'pack', 'goods', ARRAY['pharmacy'], ARRAY['dawa ya malaria', 'antimalarial', 'al']),
  ('Amoxicillin Capsules', 'Medicine', 'pack', 'goods', ARRAY['pharmacy'], ARRAY['amoxil', 'amoxicillin']),
  ('Cough Syrup', 'Medicine', 'bottle', 'goods', ARRAY['pharmacy'], ARRAY['dawa ya kikohozi', 'cough syrup']),
  ('Oral Rehydration Salts', 'Medicine', 'sachet', 'goods', ARRAY['pharmacy'], ARRAY['ors', 'oral rehydration']),
  ('Antihistamine Tablets', 'Medicine', 'pack', 'goods', ARRAY['pharmacy'], ARRAY['piriton', 'antihistamine']),
  ('Antacid Tablets', 'Medicine', 'pack', 'goods', ARRAY['pharmacy'], ARRAY['antacid', 'eno', 'dawa ya tumbo']),
  ('Deworming Tablets', 'Medicine', 'pack', 'goods', ARRAY['pharmacy'], ARRAY['dawa ya minyoo', 'deworming']),
  ('Multivitamins', 'Medicine', 'pack', 'goods', ARRAY['pharmacy'], ARRAY['vitamins', 'multivitamin']),
  ('Eye Drops', 'Medicine', 'bottle', 'goods', ARRAY['pharmacy'], ARRAY['eye drops', 'dawa ya macho']),
  ('Antiseptic Solution', 'Medicine', 'bottle', 'goods', ARRAY['duka', 'mini_supermarket', 'pharmacy'], ARRAY['dettol', 'antiseptic']),
  ('Surgical Spirit', 'Medicine', 'bottle', 'goods', ARRAY['pharmacy'], ARRAY['surgical spirit', 'spirit']),
  ('Bandage', 'Medical supplies', 'piece', 'goods', ARRAY['pharmacy'], ARRAY['bandeji', 'bandage']),
  ('Cotton Wool', 'Medical supplies', 'pack', 'goods', ARRAY['pharmacy'], ARRAY['pamba', 'cotton wool']),
  ('Gauze', 'Medical supplies', 'pack', 'goods', ARRAY['pharmacy'], ARRAY['gauze']),
  ('Plasters', 'Medical supplies', 'pack', 'goods', ARRAY['pharmacy'], ARRAY['plaster', 'band aid', 'elastoplast']),
  ('Syringe', 'Medical supplies', 'piece', 'goods', ARRAY['pharmacy'], ARRAY['sindano', 'syringe']),
  ('Gloves', 'Medical supplies', 'pair', 'goods', ARRAY['pharmacy'], ARRAY['gloves', 'mipira ya mikono']),
  ('Face Mask', 'Medical supplies', 'piece', 'goods', ARRAY['pharmacy'], ARRAY['mask', 'face mask']),
  ('Thermometer', 'Medical supplies', 'piece', 'goods', ARRAY['pharmacy'], ARRAY['thermometer', 'kipima joto']),
  ('Pregnancy Test Kit', 'Medical supplies', 'piece', 'goods', ARRAY['pharmacy'], ARRAY['pregnancy test', 'kipimo cha ujauzito']),
  ('Condoms', 'Medical supplies', 'pack', 'goods', ARRAY['duka', 'mini_supermarket', 'pharmacy'], ARRAY['condom', 'kondom']),
  ('Hand Sanitizer', 'Medical supplies', 'bottle', 'goods', ARRAY['duka', 'mini_supermarket', 'pharmacy'], ARRAY['sanitizer', 'hand sanitizer']),
  ('First Aid Kit', 'Medical supplies', 'piece', 'goods', ARRAY['pharmacy'], ARRAY['first aid kit']),
  ('Blood Pressure Check', 'Medical services', 'service', 'service', ARRAY['pharmacy'], ARRAY['bp check', 'blood pressure']),
  ('Injection', 'Medical services', 'service', 'service', ARRAY['pharmacy'], ARRAY['sindano', 'injection']),
  ('Consultation', 'Medical services', 'service', 'service', ARRAY['pharmacy'], ARRAY['consultation', 'ushauri']),
  ('Dairy Meal 70kg', 'Animal feed', '70kg', 'goods', ARRAY['agrovet'], ARRAY['dairy meal', 'chakula cha ngombe']),
  ('Layers Mash 70kg', 'Animal feed', '70kg', 'goods', ARRAY['agrovet', 'poultry_dairy'], ARRAY['layers mash']),
  ('Chick Mash 20kg', 'Animal feed', '20kg', 'goods', ARRAY['agrovet', 'poultry_dairy'], ARRAY['chick mash']),
  ('Growers Mash 50kg', 'Animal feed', '50kg', 'goods', ARRAY['agrovet'], ARRAY['growers mash']),
  ('Pig Feed 50kg', 'Animal feed', '50kg', 'goods', ARRAY['agrovet'], ARRAY['pig feed']),
  ('Mineral Salts', 'Animal feed', 'kg', 'goods', ARRAY['agrovet'], ARRAY['mineral salts', 'chumvi ya mifugo']),
  ('Dewormer', 'Veterinary', 'bottle', 'goods', ARRAY['agrovet'], ARRAY['dewormer', 'dawa ya minyoo ya mifugo']),
  ('Acaricide', 'Veterinary', 'bottle', 'goods', ARRAY['agrovet'], ARRAY['acaricide', 'dawa ya kupe']),
  ('Animal Vaccine', 'Veterinary', 'dose', 'goods', ARRAY['agrovet'], ARRAY['chanjo', 'vaccine']),
  ('Maize Seed 2kg', 'Seeds', '2kg', 'goods', ARRAY['agrovet'], ARRAY['mbegu za mahindi', 'maize seed']),
  ('Bean Seed 2kg', 'Seeds', '2kg', 'goods', ARRAY['agrovet'], ARRAY['mbegu za maharagwe', 'bean seed']),
  ('Vegetable Seeds', 'Seeds', 'packet', 'goods', ARRAY['agrovet', 'plant_shop'], ARRAY['mbegu za mboga', 'vegetable seeds']),
  ('DAP Fertiliser 50kg', 'Fertiliser', '50kg', 'goods', ARRAY['agrovet'], ARRAY['dap', 'mbolea']),
  ('CAN Fertiliser 50kg', 'Fertiliser', '50kg', 'goods', ARRAY['agrovet'], ARRAY['can fertiliser', 'mbolea ya can']),
  ('NPK Fertiliser 50kg', 'Fertiliser', '50kg', 'goods', ARRAY['agrovet'], ARRAY['npk']),
  ('Pesticide', 'Agrochemicals', 'bottle', 'goods', ARRAY['agrovet'], ARRAY['dawa ya wadudu', 'pesticide']),
  ('Herbicide', 'Agrochemicals', 'bottle', 'goods', ARRAY['agrovet'], ARRAY['herbicide', 'dawa ya magugu']),
  ('Braiding', 'Hair', 'service', 'service', ARRAY['salon'], ARRAY['kusuka', 'braiding', 'braids']),
  ('Weaving', 'Hair', 'service', 'service', ARRAY['salon'], ARRAY['weaving', 'weave']),
  ('Cornrows', 'Hair', 'service', 'service', ARRAY['salon'], ARRAY['lines', 'cornrows', 'mistari']),
  ('Twists', 'Hair', 'service', 'service', ARRAY['salon'], ARRAY['twists']),
  ('Dreadlocks', 'Hair', 'service', 'service', ARRAY['kinyozi', 'salon'], ARRAY['dreadlocks', 'rasta', 'locs']),
  ('Wash and Set', 'Hair', 'service', 'service', ARRAY['salon'], ARRAY['wash and set', 'kuosha nywele']),
  ('Blow Dry', 'Hair', 'service', 'service', ARRAY['salon'], ARRAY['blow dry']),
  ('Relaxer Retouch', 'Hair', 'service', 'service', ARRAY['salon'], ARRAY['retouch', 'relaxer']),
  ('Hair Treatment', 'Hair', 'service', 'service', ARRAY['salon'], ARRAY['treatment', 'hair treatment']),
  ('Hair Dye', 'Hair', 'service', 'service', ARRAY['kinyozi', 'salon'], ARRAY['dye', 'rangi ya nywele']),
  ('Wig Installation', 'Hair', 'service', 'service', ARRAY['salon'], ARRAY['wig installation', 'wig fitting']),
  ('Ladies Haircut', 'Hair', 'service', 'service', ARRAY['salon'], ARRAY['ladies haircut', 'kukata nywele']),
  ('Haircut', 'Hair', 'service', 'service', ARRAY['kinyozi'], ARRAY['kunyoa', 'haircut', 'shave']),
  ('Kids Haircut', 'Hair', 'service', 'service', ARRAY['kinyozi'], ARRAY['kids haircut', 'kunyoa mtoto']),
  ('Beard Trim', 'Hair', 'service', 'service', ARRAY['kinyozi'], ARRAY['beard trim', 'ndevu']),
  ('Lining', 'Hair', 'service', 'service', ARRAY['kinyozi'], ARRAY['lining', 'shape up']),
  ('Head Wash', 'Hair', 'service', 'service', ARRAY['kinyozi'], ARRAY['head wash', 'kuosha kichwa']),
  ('Head Massage', 'Hair', 'service', 'service', ARRAY['kinyozi'], ARRAY['massage', 'head massage']),
  ('Manicure', 'Nails', 'service', 'service', ARRAY['nail_shop', 'salon'], ARRAY['manicure']),
  ('Pedicure', 'Nails', 'service', 'service', ARRAY['nail_shop', 'salon'], ARRAY['pedicure']),
  ('Gel Nails', 'Nails', 'service', 'service', ARRAY['nail_shop'], ARRAY['gel nails', 'gel']),
  ('Acrylic Nails', 'Nails', 'service', 'service', ARRAY['nail_shop'], ARRAY['acrylic', 'acrylic nails']),
  ('Nail Art', 'Nails', 'service', 'service', ARRAY['nail_shop'], ARRAY['nail art']),
  ('Polish Change', 'Nails', 'service', 'service', ARRAY['nail_shop'], ARRAY['polish change']),
  ('Nail Refill', 'Nails', 'service', 'service', ARRAY['nail_shop'], ARRAY['refill', 'nail refill']),
  ('Braids Packet', 'Hair products', 'packet', 'goods', ARRAY['beauty_shop', 'salon'], ARRAY['braids', 'darling', 'nywele za kusuka']),
  ('Weave', 'Hair products', 'piece', 'goods', ARRAY['beauty_shop', 'salon'], ARRAY['weave', 'nywele']),
  ('Wig', 'Hair products', 'piece', 'goods', ARRAY['beauty_shop', 'salon'], ARRAY['wig']),
  ('Hair Food', 'Hair products', 'jar', 'goods', ARRAY['beauty_shop'], ARRAY['hair food', 'mafuta ya nywele']),
  ('Relaxer Kit', 'Hair products', 'piece', 'goods', ARRAY['beauty_shop', 'salon'], ARRAY['relaxer', 'dawa ya nywele']),
  ('Hair Conditioner', 'Hair products', 'bottle', 'goods', ARRAY['beauty_shop', 'salon'], ARRAY['conditioner']),
  ('Hair Oil', 'Hair products', 'bottle', 'goods', ARRAY['beauty_shop'], ARRAY['hair oil', 'mafuta ya nywele']),
  ('Comb', 'Hair products', 'piece', 'goods', ARRAY['beauty_shop'], ARRAY['kitana', 'comb']),
  ('Hair Brush', 'Hair products', 'piece', 'goods', ARRAY['beauty_shop'], ARRAY['brush', 'hair brush']),
  ('Hair Pins', 'Hair products', 'pack', 'goods', ARRAY['beauty_shop'], ARRAY['pins', 'hair pins']),
  ('Nail Polish', 'Cosmetics', 'piece', 'goods', ARRAY['beauty_shop', 'nail_shop'], ARRAY['nail polish', 'rangi ya kucha']),
  ('Lipstick', 'Cosmetics', 'piece', 'goods', ARRAY['beauty_shop'], ARRAY['lipstick', 'rangi ya midomo']),
  ('Foundation', 'Cosmetics', 'piece', 'goods', ARRAY['beauty_shop'], ARRAY['foundation']),
  ('Face Powder', 'Cosmetics', 'piece', 'goods', ARRAY['beauty_shop'], ARRAY['powder', 'face powder']),
  ('Mascara', 'Cosmetics', 'piece', 'goods', ARRAY['beauty_shop'], ARRAY['mascara']),
  ('Eyeliner', 'Cosmetics', 'piece', 'goods', ARRAY['beauty_shop'], ARRAY['eyeliner']),
  ('False Lashes', 'Cosmetics', 'pair', 'goods', ARRAY['beauty_shop'], ARRAY['lashes', 'false lashes']),
  ('Makeup Brushes', 'Cosmetics', 'set', 'goods', ARRAY['beauty_shop'], ARRAY['makeup brushes']),
  ('Perfume', 'Cosmetics', 'bottle', 'goods', ARRAY['beauty_shop'], ARRAY['perfume', 'marashi']),
  ('Body Spray', 'Cosmetics', 'can', 'goods', ARRAY['beauty_shop'], ARRAY['body spray', 'spray']),
  ('Cement 50kg', 'Building', '50kg', 'goods', ARRAY['hardware'], ARRAY['cement', 'simiti']),
  ('Nails 1kg', 'Building', '1kg', 'goods', ARRAY['hardware'], ARRAY['misumari', 'nails']),
  ('Roofing Nails 1kg', 'Building', '1kg', 'goods', ARRAY['hardware'], ARRAY['misumari ya mabati', 'roofing nails']),
  ('Iron Sheet', 'Building', 'piece', 'goods', ARRAY['hardware'], ARRAY['mabati', 'iron sheet']),
  ('Timber', 'Building', 'piece', 'goods', ARRAY['hardware'], ARRAY['mbao', 'timber']),
  ('Sand', 'Building', 'tonne', 'goods', ARRAY['hardware'], ARRAY['mchanga', 'sand']),
  ('Ballast', 'Building', 'tonne', 'goods', ARRAY['hardware'], ARRAY['kokoto', 'ballast']),
  ('Binding Wire 1kg', 'Building', '1kg', 'goods', ARRAY['hardware'], ARRAY['waya', 'binding wire']),
  ('Paint 1L', 'Building', '1L', 'goods', ARRAY['hardware'], ARRAY['rangi', 'paint']),
  ('Paint 4L', 'Building', '4L', 'goods', ARRAY['hardware'], ARRAY['rangi 4l', 'paint 4 litre']),
  ('Paint Brush', 'Building', 'piece', 'goods', ARRAY['hardware'], ARRAY['brashi', 'paint brush']),
  ('PVC Pipe', 'Plumbing', 'piece', 'goods', ARRAY['hardware'], ARRAY['bomba', 'pvc pipe']),
  ('Tap', 'Plumbing', 'piece', 'goods', ARRAY['hardware'], ARRAY['mfereji', 'tap']),
  ('Elbow Joint', 'Plumbing', 'piece', 'goods', ARRAY['hardware'], ARRAY['elbow', 'joint']),
  ('Electric Cable', 'Electrical', 'metre', 'goods', ARRAY['electronics', 'hardware'], ARRAY['cable', 'waya wa stima']),
  ('Socket', 'Electrical', 'piece', 'goods', ARRAY['electronics', 'hardware'], ARRAY['socket', 'plagi']),
  ('Switch', 'Electrical', 'piece', 'goods', ARRAY['electronics', 'hardware'], ARRAY['switch', 'swichi']),
  ('Light Bulb', 'Electrical', 'piece', 'goods', ARRAY['duka', 'hardware', 'mini_supermarket'], ARRAY['bulb', 'taa', 'globe']),
  ('Padlock', 'Tools', 'piece', 'goods', ARRAY['hardware'], ARRAY['kufuli', 'padlock']),
  ('Hammer', 'Tools', 'piece', 'goods', ARRAY['hardware'], ARRAY['nyundo', 'hammer']),
  ('Pliers', 'Tools', 'piece', 'goods', ARRAY['hardware'], ARRAY['koleo', 'pliers']),
  ('Screwdriver', 'Tools', 'piece', 'goods', ARRAY['hardware'], ARRAY['screwdriver', 'bisibisi']),
  ('Tape Measure', 'Tools', 'piece', 'goods', ARRAY['hardware'], ARRAY['tape measure']),
  ('Spade', 'Tools', 'piece', 'goods', ARRAY['agrovet', 'hardware'], ARRAY['sepetu', 'spade']),
  ('Jembe', 'Tools', 'piece', 'goods', ARRAY['agrovet', 'hardware'], ARRAY['jembe', 'hoe']),
  ('Panga', 'Tools', 'piece', 'goods', ARRAY['agrovet', 'hardware'], ARRAY['panga', 'machete']),
  ('Wheelbarrow', 'Tools', 'piece', 'goods', ARRAY['hardware'], ARRAY['kerandi', 'wheelbarrow']),
  ('Grinding Disc', 'Tools', 'piece', 'goods', ARRAY['hardware'], ARRAY['grinding disc']),
  ('Welding Rods', 'Tools', 'pack', 'goods', ARRAY['hardware'], ARRAY['welding rods']),
  ('Sandpaper', 'Tools', 'piece', 'goods', ARRAY['furniture_hardware', 'hardware'], ARRAY['sandpaper']),
  ('Silicone Sealant', 'Building', 'tube', 'goods', ARRAY['hardware'], ARRAY['silicone']),
  ('Hinges', 'Fittings', 'pair', 'goods', ARRAY['furniture_hardware', 'hardware'], ARRAY['bawaba', 'hinges']),
  ('Door Handle', 'Fittings', 'piece', 'goods', ARRAY['furniture_hardware', 'hardware'], ARRAY['handle', 'kitasa']),
  ('Screws', 'Fittings', 'pack', 'goods', ARRAY['furniture_hardware', 'hardware'], ARRAY['screws', 'skrubu']),
  ('Wood Glue', 'Fittings', 'bottle', 'goods', ARRAY['furniture_hardware'], ARRAY['wood glue', 'gundi']),
  ('Varnish', 'Fittings', 'tin', 'goods', ARRAY['furniture_hardware'], ARRAY['varnish', 'rangi ya mbao']),
  ('Drawer Runners', 'Fittings', 'pair', 'goods', ARRAY['furniture_hardware'], ARRAY['drawer runners']),
  ('Castor Wheels', 'Fittings', 'piece', 'goods', ARRAY['furniture_hardware'], ARRAY['castor wheels', 'magurudumu']),
  ('Upholstery Foam', 'Fittings', 'piece', 'goods', ARRAY['furniture_hardware'], ARRAY['foam', 'sponji']),
  ('Upholstery Fabric', 'Fittings', 'metre', 'goods', ARRAY['furniture_hardware', 'tailoring'], ARRAY['fabric', 'kitambaa']),
  ('Wood Polish', 'Fittings', 'tin', 'goods', ARRAY['furniture_hardware'], ARRAY['wood polish']),
  ('Bucket', 'Homeware', 'piece', 'goods', ARRAY['duka', 'household_goods', 'mini_supermarket'], ARRAY['ndoo', 'bucket']),
  ('Basin', 'Homeware', 'piece', 'goods', ARRAY['household_goods'], ARRAY['karai', 'basin']),
  ('Jug', 'Homeware', 'piece', 'goods', ARRAY['household_goods'], ARRAY['jagi', 'jug']),
  ('Cups', 'Homeware', 'piece', 'goods', ARRAY['household_goods'], ARRAY['vikombe', 'cups']),
  ('Plates', 'Homeware', 'piece', 'goods', ARRAY['household_goods'], ARRAY['sahani', 'plates']),
  ('Glasses', 'Homeware', 'piece', 'goods', ARRAY['household_goods'], ARRAY['glasi', 'glasses']),
  ('Sufuria', 'Homeware', 'piece', 'goods', ARRAY['household_goods'], ARRAY['sufuria', 'cooking pot']),
  ('Frying Pan', 'Homeware', 'piece', 'goods', ARRAY['household_goods'], ARRAY['frying pan', 'kikaango']),
  ('Kettle', 'Homeware', 'piece', 'goods', ARRAY['household_goods'], ARRAY['birika', 'kettle']),
  ('Thermos Flask', 'Homeware', 'piece', 'goods', ARRAY['household_goods'], ARRAY['thermos', 'flask']),
  ('Cutlery Set', 'Homeware', 'set', 'goods', ARRAY['household_goods'], ARRAY['vijiko', 'cutlery']),
  ('Kitchen Knife', 'Homeware', 'piece', 'goods', ARRAY['household_goods'], ARRAY['kisu', 'knife']),
  ('Chopping Board', 'Homeware', 'piece', 'goods', ARRAY['household_goods'], ARRAY['chopping board']),
  ('Mop', 'Homeware', 'piece', 'goods', ARRAY['duka', 'household_goods', 'mini_supermarket'], ARRAY['mop']),
  ('Broom', 'Homeware', 'piece', 'goods', ARRAY['duka', 'household_goods', 'mini_supermarket'], ARRAY['ufagio', 'broom']),
  ('Dustpan', 'Homeware', 'piece', 'goods', ARRAY['household_goods'], ARRAY['dustpan']),
  ('Clothes Hangers', 'Homeware', 'pack', 'goods', ARRAY['household_goods'], ARRAY['hangers']),
  ('Laundry Basket', 'Homeware', 'piece', 'goods', ARRAY['household_goods'], ARRAY['laundry basket']),
  ('Dustbin', 'Homeware', 'piece', 'goods', ARRAY['household_goods'], ARRAY['dustbin', 'pipa']),
  ('Door Mat', 'Homeware', 'piece', 'goods', ARRAY['household_goods'], ARRAY['mat', 'door mat']),
  ('Curtains', 'Homeware', 'pair', 'goods', ARRAY['household_goods'], ARRAY['pazia', 'curtains']),
  ('Bedsheets', 'Homeware', 'set', 'goods', ARRAY['household_goods'], ARRAY['shuka', 'bedsheets']),
  ('Blanket', 'Homeware', 'piece', 'goods', ARRAY['household_goods'], ARRAY['blanketi', 'blanket']),
  ('Towel', 'Homeware', 'piece', 'goods', ARRAY['household_goods'], ARRAY['taulo', 'towel']),
  ('Pillow', 'Homeware', 'piece', 'goods', ARRAY['household_goods'], ARRAY['mto', 'pillow']),
  ('Jiko', 'Homeware', 'piece', 'goods', ARRAY['household_goods'], ARRAY['jiko', 'charcoal stove']),
  ('Gas Burner', 'Homeware', 'piece', 'goods', ARRAY['gas_distribution', 'household_goods'], ARRAY['gas burner', 'meko']),
  ('Water Dispenser', 'Homeware', 'piece', 'goods', ARRAY['household_goods', 'water_refill'], ARRAY['water dispenser']),
  ('Storage Container', 'Homeware', 'piece', 'goods', ARRAY['household_goods'], ARRAY['container', 'chombo']),
  ('Jerrycan', 'Homeware', 'piece', 'goods', ARRAY['household_goods', 'water_refill'], ARRAY['mtungi', 'jerrycan']),
  ('Exercise Book', 'Stationery', 'piece', 'goods', ARRAY['bookshop', 'duka', 'mini_supermarket'], ARRAY['daftari', 'exercise book']),
  ('Counter Book', 'Stationery', 'piece', 'goods', ARRAY['bookshop'], ARRAY['counter book', 'register']),
  ('Graph Book', 'Stationery', 'piece', 'goods', ARRAY['bookshop'], ARRAY['graph book']),
  ('Textbook', 'Stationery', 'piece', 'goods', ARRAY['bookshop'], ARRAY['textbook', 'kitabu']),
  ('Pen', 'Stationery', 'piece', 'goods', ARRAY['bookshop', 'duka', 'mini_supermarket'], ARRAY['kalamu', 'pen', 'biro']),
  ('Pencil', 'Stationery', 'piece', 'goods', ARRAY['bookshop', 'duka', 'mini_supermarket'], ARRAY['penseli', 'pencil']),
  ('Ruler', 'Stationery', 'piece', 'goods', ARRAY['bookshop'], ARRAY['rula', 'ruler']),
  ('Eraser', 'Stationery', 'piece', 'goods', ARRAY['bookshop'], ARRAY['raba', 'eraser', 'rubber']),
  ('Sharpener', 'Stationery', 'piece', 'goods', ARRAY['bookshop'], ARRAY['sharpener']),
  ('Geometry Set', 'Stationery', 'set', 'goods', ARRAY['bookshop'], ARRAY['geometry set', 'mathematical set']),
  ('Crayons', 'Stationery', 'pack', 'goods', ARRAY['bookshop'], ARRAY['crayons']),
  ('Coloured Pencils', 'Stationery', 'pack', 'goods', ARRAY['bookshop'], ARRAY['colour pencils']),
  ('Manila Paper', 'Stationery', 'piece', 'goods', ARRAY['bookshop'], ARRAY['manila', 'manila paper']),
  ('Printing Paper Ream', 'Stationery', 'ream', 'goods', ARRAY['bookshop', 'cyber'], ARRAY['ream', 'printing paper', 'a4 paper']),
  ('Glue Stick', 'Stationery', 'piece', 'goods', ARRAY['bookshop'], ARRAY['gundi', 'glue']),
  ('Stapler', 'Stationery', 'piece', 'goods', ARRAY['bookshop'], ARRAY['stapler']),
  ('Staples', 'Stationery', 'box', 'goods', ARRAY['bookshop'], ARRAY['staples']),
  ('File', 'Stationery', 'piece', 'goods', ARRAY['bookshop'], ARRAY['file', 'folda']),
  ('Envelope', 'Stationery', 'piece', 'goods', ARRAY['bookshop'], ARRAY['bahasha', 'envelope']),
  ('Calculator', 'Stationery', 'piece', 'goods', ARRAY['bookshop'], ARRAY['calculator']),
  ('School Bag', 'Stationery', 'piece', 'goods', ARRAY['bookshop'], ARRAY['school bag', 'mkoba']),
  ('Chalk', 'Stationery', 'box', 'goods', ARRAY['bookshop'], ARRAY['chaki', 'chalk']),
  ('Whiteboard Marker', 'Stationery', 'piece', 'goods', ARRAY['bookshop'], ARRAY['marker', 'whiteboard marker']),
  ('Receipt Book', 'Stationery', 'piece', 'goods', ARRAY['bookshop', 'duka', 'mini_supermarket'], ARRAY['receipt book', 'risiti']),
  ('Printing Black and White', 'Cyber services', 'service', 'service', ARRAY['cyber'], ARRAY['printing', 'print']),
  ('Printing Colour', 'Cyber services', 'service', 'service', ARRAY['cyber'], ARRAY['colour printing', 'color print']),
  ('Photocopy', 'Cyber services', 'service', 'service', ARRAY['cyber'], ARRAY['photocopy', 'copy']),
  ('Lamination', 'Cyber services', 'service', 'service', ARRAY['cyber'], ARRAY['lamination', 'laminate']),
  ('Scanning', 'Cyber services', 'service', 'service', ARRAY['cyber'], ARRAY['scanning', 'scan']),
  ('Typing', 'Cyber services', 'service', 'service', ARRAY['cyber'], ARRAY['typing']),
  ('Binding', 'Cyber services', 'service', 'service', ARRAY['cyber'], ARRAY['binding', 'spiral binding']),
  ('Passport Photos', 'Cyber services', 'service', 'service', ARRAY['cyber'], ARRAY['passport photo', 'photos']),
  ('Internet Browsing', 'Cyber services', 'service', 'service', ARRAY['cyber'], ARRAY['browsing', 'internet']),
  ('CV Writing', 'Cyber services', 'service', 'service', ARRAY['cyber'], ARRAY['cv', 'cv writing']),
  ('eCitizen Services', 'Cyber services', 'service', 'service', ARRAY['cyber'], ARRAY['ecitizen', 'government services']),
  ('KRA Services', 'Cyber services', 'service', 'service', ARRAY['cyber'], ARRAY['kra', 'kra returns', 'pin']),
  ('Phone Charger', 'Electronics', 'piece', 'goods', ARRAY['duka', 'electronics', 'mini_supermarket'], ARRAY['charger', 'chaja']),
  ('Earphones', 'Electronics', 'piece', 'goods', ARRAY['duka', 'electronics', 'mini_supermarket'], ARRAY['earphones', 'earpods']),
  ('Headphones', 'Electronics', 'piece', 'goods', ARRAY['electronics'], ARRAY['headphones']),
  ('Screen Protector', 'Electronics', 'piece', 'goods', ARRAY['electronics'], ARRAY['screen protector', 'tempered glass']),
  ('Phone Case', 'Electronics', 'piece', 'goods', ARRAY['electronics'], ARRAY['phone case', 'cover']),
  ('Memory Card', 'Electronics', 'piece', 'goods', ARRAY['electronics'], ARRAY['memory card', 'sd card']),
  ('Flash Disk', 'Electronics', 'piece', 'goods', ARRAY['cyber', 'electronics'], ARRAY['flash disk', 'usb']),
  ('Power Bank', 'Electronics', 'piece', 'goods', ARRAY['electronics'], ARRAY['power bank']),
  ('USB Cable', 'Electronics', 'piece', 'goods', ARRAY['electronics'], ARRAY['usb cable', 'cable']),
  ('Extension Cable', 'Electronics', 'piece', 'goods', ARRAY['electronics', 'hardware'], ARRAY['extension', 'extension cable']),
  ('Radio', 'Electronics', 'piece', 'goods', ARRAY['electronics'], ARRAY['radio']),
  ('Bluetooth Speaker', 'Electronics', 'piece', 'goods', ARRAY['electronics'], ARRAY['speaker', 'bluetooth speaker']),
  ('TV Aerial', 'Electronics', 'piece', 'goods', ARRAY['electronics'], ARRAY['aerial', 'antenna']),
  ('Sim Card', 'Electronics', 'piece', 'goods', ARRAY['duka', 'electronics', 'mini_supermarket'], ARRAY['sim card', 'line']),
  ('Phone Adapter', 'Electronics', 'piece', 'goods', ARRAY['electronics'], ARRAY['adapter']),
  ('Screen Replacement', 'Phone repair', 'service', 'service', ARRAY['phone_repair'], ARRAY['screen replacement', 'kubadilisha screen']),
  ('Battery Replacement', 'Phone repair', 'service', 'service', ARRAY['phone_repair'], ARRAY['battery replacement']),
  ('Charging Port Repair', 'Phone repair', 'service', 'service', ARRAY['phone_repair'], ARRAY['charging port', 'port repair']),
  ('Software Update', 'Phone repair', 'service', 'service', ARRAY['phone_repair'], ARRAY['software', 'flashing']),
  ('Phone Unlocking', 'Phone repair', 'service', 'service', ARRAY['phone_repair'], ARRAY['unlocking', 'unlock']),
  ('Phone Diagnostics', 'Phone repair', 'service', 'service', ARRAY['phone_repair'], ARRAY['diagnostics', 'checking']),
  ('Phone Charging', 'Phone repair', 'service', 'service', ARRAY['duka', 'mini_supermarket', 'phone_repair'], ARRAY['charging', 'kucharge']),
  ('Seedlings', 'Plants', 'piece', 'goods', ARRAY['agrovet', 'plant_shop'], ARRAY['miche', 'seedlings']),
  ('Potted Plant', 'Plants', 'piece', 'goods', ARRAY['plant_shop'], ARRAY['potted plant', 'mmea']),
  ('Flower Pot', 'Plants', 'piece', 'goods', ARRAY['plant_shop'], ARRAY['chungu cha maua', 'flower pot']),
  ('Garden Soil', 'Plants', 'bag', 'goods', ARRAY['plant_shop'], ARRAY['udongo', 'garden soil']),
  ('Manure', 'Plants', 'bag', 'goods', ARRAY['agrovet', 'plant_shop'], ARRAY['samadi', 'manure']),
  ('Ornamental Plant', 'Plants', 'piece', 'goods', ARRAY['plant_shop'], ARRAY['ornamental', 'flower plant']),
  ('Grass Sod', 'Plants', 'sqm', 'goods', ARRAY['plant_shop'], ARRAY['nyasi', 'grass']),
  ('Watering Can', 'Plants', 'piece', 'goods', ARRAY['plant_shop'], ARRAY['watering can']),
  ('Pruning Shears', 'Plants', 'piece', 'goods', ARRAY['plant_shop'], ARRAY['secateurs', 'pruning shears']),
  ('Plant Food', 'Plants', 'bottle', 'goods', ARRAY['plant_shop'], ARRAY['plant food', 'mbolea ya maua']),
  ('Water Refill 10L', 'Water', '10L', 'goods', ARRAY['water_refill'], ARRAY['refill 10l', 'maji 10l']),
  ('Water Refill 20L', 'Water', '20L', 'goods', ARRAY['water_refill'], ARRAY['refill 20l', 'maji 20l']),
  ('Water Refill 5L', 'Water', '5L', 'goods', ARRAY['water_refill'], ARRAY['refill 5l', 'maji 5l']),
  ('Dispenser Bottle', 'Water', 'piece', 'goods', ARRAY['water_refill'], ARRAY['dispenser bottle', 'chupa ya dispenser']),
  ('Water Delivery', 'Water', 'service', 'service', ARRAY['water_refill'], ARRAY['delivery', 'kupeleka maji']),
  ('Maize Grain 1kg', 'Grains', '1kg', 'goods', ARRAY['grains_store'], ARRAY['mahindi', 'maize']),
  ('Maize Grain 90kg', 'Grains', '90kg', 'goods', ARRAY['grains_store'], ARRAY['gunia la mahindi', 'maize bag']),
  ('Millet 1kg', 'Grains', '1kg', 'goods', ARRAY['grains_store'], ARRAY['wimbi', 'millet']),
  ('Sorghum 1kg', 'Grains', '1kg', 'goods', ARRAY['grains_store'], ARRAY['mtama', 'sorghum']),
  ('Cowpeas 1kg', 'Grains', '1kg', 'goods', ARRAY['grains_store'], ARRAY['kunde', 'cowpeas']),
  ('Njahi 1kg', 'Grains', '1kg', 'goods', ARRAY['grains_store'], ARRAY['njahi', 'black beans']),
  ('Sunflower Seed 1kg', 'Grains', '1kg', 'goods', ARRAY['grains_store'], ARRAY['alizeti', 'sunflower']),
  ('Groundnuts 1kg', 'Grains', '1kg', 'goods', ARRAY['grains_store'], ARRAY['njugu', 'karanga']),
  ('Milling per Kg', 'Milling', 'service', 'service', ARRAY['posho_mill'], ARRAY['kusaga', 'milling', 'posho']),
  ('Milling per Debe', 'Milling', 'service', 'service', ARRAY['posho_mill'], ARRAY['debe', 'milling debe']),
  ('Cash Deposit', 'Mobile money', 'service', 'service', ARRAY['mpesa_agent'], ARRAY['deposit', 'kuweka pesa']),
  ('Cash Withdrawal', 'Mobile money', 'service', 'service', ARRAY['mpesa_agent'], ARRAY['withdrawal', 'kutoa pesa']),
  ('Bill Payment', 'Mobile money', 'service', 'service', ARRAY['mpesa_agent'], ARRAY['bill payment', 'kulipa bill']),
  ('Car Wash Saloon', 'Car wash', 'service', 'service', ARRAY['car_wash'], ARRAY['car wash', 'kuosha gari']),
  ('Car Wash SUV', 'Car wash', 'service', 'service', ARRAY['car_wash'], ARRAY['suv wash']),
  ('Motorbike Wash', 'Car wash', 'service', 'service', ARRAY['car_wash'], ARRAY['boda wash', 'motorbike wash']),
  ('Interior Cleaning', 'Car wash', 'service', 'service', ARRAY['car_wash'], ARRAY['interior cleaning', 'vacuum']),
  ('Engine Wash', 'Car wash', 'service', 'service', ARRAY['car_wash'], ARRAY['engine wash']),
  ('Waxing', 'Car wash', 'service', 'service', ARRAY['car_wash'], ARRAY['waxing', 'polish']),
  ('Washing per Kg', 'Laundry', 'service', 'service', ARRAY['laundry'], ARRAY['kufua', 'washing']),
  ('Dry Cleaning', 'Laundry', 'service', 'service', ARRAY['laundry'], ARRAY['dry cleaning']),
  ('Ironing', 'Laundry', 'service', 'service', ARRAY['laundry'], ARRAY['kupiga pasi', 'ironing']),
  ('Duvet Cleaning', 'Laundry', 'service', 'service', ARRAY['laundry'], ARRAY['duvet cleaning']),
  ('Suit Cleaning', 'Laundry', 'service', 'service', ARRAY['laundry'], ARRAY['suit cleaning']),
  ('Thread', 'Tailoring', 'piece', 'goods', ARRAY['tailoring'], ARRAY['uzi', 'thread']),
  ('Zip', 'Tailoring', 'piece', 'goods', ARRAY['tailoring'], ARRAY['zipu', 'zip']),
  ('Buttons', 'Tailoring', 'pack', 'goods', ARRAY['tailoring'], ARRAY['vifungo', 'buttons']),
  ('Fabric', 'Tailoring', 'metre', 'goods', ARRAY['tailoring'], ARRAY['kitambaa', 'fabric', 'material']),
  ('Elastic', 'Tailoring', 'metre', 'goods', ARRAY['tailoring'], ARRAY['elastic']),
  ('Needles', 'Tailoring', 'pack', 'goods', ARRAY['tailoring'], ARRAY['sindano', 'needles']),
  ('Dress Making', 'Tailoring', 'service', 'service', ARRAY['tailoring'], ARRAY['kushona', 'dress making']),
  ('Alteration', 'Tailoring', 'service', 'service', ARRAY['tailoring'], ARRAY['alteration', 'kurekebisha']),
  ('Hemming', 'Tailoring', 'service', 'service', ARRAY['tailoring'], ARRAY['hemming', 'kufupisha']),
  ('Clothes Repair', 'Tailoring', 'service', 'service', ARRAY['tailoring'], ARRAY['repair', 'kushona nguo']),
  ('School Uniform', 'Tailoring', 'service', 'service', ARRAY['tailoring'], ARRAY['uniform', 'sare']),
  ('Shirt', 'Clothing', 'piece', 'goods', ARRAY['boutique'], ARRAY['shati', 'shirt']),
  ('Trousers', 'Clothing', 'piece', 'goods', ARRAY['boutique'], ARRAY['suruali', 'trousers']),
  ('Dress', 'Clothing', 'piece', 'goods', ARRAY['boutique'], ARRAY['dera', 'dress']),
  ('Skirt', 'Clothing', 'piece', 'goods', ARRAY['boutique'], ARRAY['skirt', 'sketi']),
  ('T Shirt', 'Clothing', 'piece', 'goods', ARRAY['boutique'], ARRAY['t shirt', 'tshirt']),
  ('Jeans', 'Clothing', 'piece', 'goods', ARRAY['boutique'], ARRAY['jeans']),
  ('Jacket', 'Clothing', 'piece', 'goods', ARRAY['boutique'], ARRAY['jaketi', 'jacket']),
  ('Sweater', 'Clothing', 'piece', 'goods', ARRAY['boutique'], ARRAY['sweta', 'sweater']),
  ('Socks', 'Clothing', 'pair', 'goods', ARRAY['boutique', 'shoe_shop'], ARRAY['soksi', 'socks']),
  ('Underwear', 'Clothing', 'piece', 'goods', ARRAY['boutique'], ARRAY['chupi', 'underwear']),
  ('Bra', 'Clothing', 'piece', 'goods', ARRAY['boutique'], ARRAY['sidiria', 'bra']),
  ('Childrens Clothes', 'Clothing', 'piece', 'goods', ARRAY['boutique'], ARRAY['nguo za watoto', 'kids clothes']),
  ('School Uniform Set', 'Clothing', 'set', 'goods', ARRAY['boutique'], ARRAY['sare za shule', 'school uniform']),
  ('Shoes Mens', 'Footwear', 'pair', 'goods', ARRAY['shoe_shop'], ARRAY['viatu vya wanaume', 'mens shoes']),
  ('Shoes Ladies', 'Footwear', 'pair', 'goods', ARRAY['shoe_shop'], ARRAY['viatu vya wanawake', 'ladies shoes']),
  ('School Shoes', 'Footwear', 'pair', 'goods', ARRAY['shoe_shop'], ARRAY['viatu vya shule', 'school shoes']),
  ('Sandals', 'Footwear', 'pair', 'goods', ARRAY['shoe_shop'], ARRAY['sandali', 'sandals']),
  ('Slippers', 'Footwear', 'pair', 'goods', ARRAY['shoe_shop'], ARRAY['slippers', 'ndala']),
  ('Sports Shoes', 'Footwear', 'pair', 'goods', ARRAY['shoe_shop'], ARRAY['sports shoes', 'rubbers', 'sneakers']),
  ('Boots', 'Footwear', 'pair', 'goods', ARRAY['hardware', 'shoe_shop'], ARRAY['buti', 'boots', 'gumboots']),
  ('Shoe Polish', 'Footwear', 'piece', 'goods', ARRAY['duka', 'mini_supermarket', 'shoe_shop'], ARRAY['polish', 'rangi ya viatu']),
  ('Shoe Laces', 'Footwear', 'pair', 'goods', ARRAY['shoe_shop'], ARRAY['laces', 'kamba za viatu']),
  ('Cooking Gas Refill 6kg', 'Gas', '6kg', 'goods', ARRAY['duka', 'gas_distribution', 'mini_supermarket'], ARRAY['gesi 6kg', 'gas refill 6kg', 'gesi']),
  ('Cooking Gas Refill 13kg', 'Gas', '13kg', 'goods', ARRAY['duka', 'gas_distribution', 'mini_supermarket'], ARRAY['gesi 13kg', 'gas refill 13kg']),
  ('Gas Cylinder 6kg', 'Gas', 'piece', 'goods', ARRAY['gas_distribution'], ARRAY['mtungi wa gesi', 'gas cylinder']),
  ('Gas Regulator', 'Gas', 'piece', 'goods', ARRAY['gas_distribution'], ARRAY['regulator']),
  ('Gas Pipe', 'Gas', 'piece', 'goods', ARRAY['gas_distribution'], ARRAY['gas pipe']),
  ('Gas Grill', 'Gas', 'piece', 'goods', ARRAY['gas_distribution'], ARRAY['grill', 'gas grill']),
  ('Day Old Chicks', 'Poultry', 'piece', 'goods', ARRAY['poultry_dairy'], ARRAY['vifaranga', 'chicks']),
  ('Kienyeji Chicken', 'Poultry', 'piece', 'goods', ARRAY['poultry_dairy'], ARRAY['kuku kienyeji', 'local chicken']),
  ('Broiler Chicken', 'Poultry', 'piece', 'goods', ARRAY['poultry_dairy'], ARRAY['broiler'])
ON CONFLICT (name) DO UPDATE
  SET category = EXCLUDED.category,
      pack_size = EXCLUDED.pack_size,
      kind = EXCLUDED.kind,
      business_types = EXCLUDED.business_types,
      aliases = EXCLUDED.aliases;
