-- Brand and size become their own columns, and the brand-led group gets filled in.
--
-- "Beer 500ml" smashed three separate facts into one string: what kind of thing
-- it is, who made it, and how much of it there is. That was tolerable while
-- every entry was generic. It stops being tolerable the moment a liquor store
-- opens the app, because nobody walks in and asks for "a beer", they ask for a
-- Tusker, and a catalogue that cannot say Tusker is no use to them.
--
-- Brand stays a column rather than becoming its own table. Rows are cheap and a
-- join on every keystroke is not, and the suggestion matcher runs on the phone
-- where it would have to assemble display names itself. Keeping it a column
-- still leaves the grouping the reporting needs: product_type plus brand plus
-- size is exactly the price comparison, and it is impossible while the brand is
-- buried inside a name.
--
-- The generic row survives alongside every branded one. A shop selling a beer
-- nobody has listed still needs something to tap.

ALTER TABLE public.canonical_products
  ADD COLUMN IF NOT EXISTS product_type TEXT,
  ADD COLUMN IF NOT EXISTS brand TEXT,
  ADD COLUMN IF NOT EXISTS size_value NUMERIC,
  ADD COLUMN IF NOT EXISTS size_unit TEXT;

-- How the thing is priced, which is a different question from how big it is.
--
-- The distinction the old single column could not make: a pack_size of "1kg" is
-- a sealed one-kilo packet handed over as one thing, while "kg" means loose and
-- weighed at the counter. Same letters, different sale. Reading one as the other
-- turns every price per kilo into a price per packet.
ALTER TABLE public.canonical_products
  ADD COLUMN IF NOT EXISTS sold_by TEXT NOT NULL DEFAULT 'unit';

ALTER TABLE public.canonical_products
  DROP CONSTRAINT IF EXISTS canonical_products_sold_by_check;
ALTER TABLE public.canonical_products
  ADD CONSTRAINT canonical_products_sold_by_check
  CHECK (sold_by IN ('unit', 'weight', 'volume', 'length', 'area', 'service'));

-- Backfill, derived from the names that shipped rather than retyped, so the two
-- cannot disagree about what "Cooking Oil 2L" was supposed to mean.
UPDATE public.canonical_products AS c
SET product_type = v.product_type,
    size_value   = v.size_value,
    size_unit    = v.size_unit,
    sold_by      = v.sold_by
FROM (VALUES
  ('Maize Flour 1kg', 'Maize Flour', 1, 'kg', 'unit'),
  ('Maize Flour 2kg', 'Maize Flour', 2, 'kg', 'unit'),
  ('Wheat Flour 1kg', 'Wheat Flour', 1, 'kg', 'unit'),
  ('Wheat Flour 2kg', 'Wheat Flour', 2, 'kg', 'unit'),
  ('Rice 1kg', 'Rice', 1, 'kg', 'unit'),
  ('Rice 2kg', 'Rice', 2, 'kg', 'unit'),
  ('Rice 5kg', 'Rice', 5, 'kg', 'unit'),
  ('Sugar 500g', 'Sugar', 500, 'g', 'unit'),
  ('Sugar 1kg', 'Sugar', 1, 'kg', 'unit'),
  ('Sugar 2kg', 'Sugar', 2, 'kg', 'unit'),
  ('Salt 500g', 'Salt', 500, 'g', 'unit'),
  ('Cooking Salt 1kg', 'Cooking Salt', 1, 'kg', 'unit'),
  ('Cooking Oil 500ml', 'Cooking Oil', 500, 'ml', 'unit'),
  ('Cooking Oil 1L', 'Cooking Oil', 1, 'l', 'unit'),
  ('Cooking Oil 2L', 'Cooking Oil', 2, 'l', 'unit'),
  ('Cooking Oil 3L', 'Cooking Oil', 3, 'l', 'unit'),
  ('Cooking Fat 500g', 'Cooking Fat', 500, 'g', 'unit'),
  ('Beans 1kg', 'Beans', 1, 'kg', 'unit'),
  ('Green Grams 1kg', 'Green Grams', 1, 'kg', 'unit'),
  ('Lentils 1kg', 'Lentils', 1, 'kg', 'unit'),
  ('Spaghetti 500g', 'Spaghetti', 500, 'g', 'unit'),
  ('Macaroni 500g', 'Macaroni', 500, 'g', 'unit'),
  ('Fresh Milk 500ml', 'Fresh Milk', 500, 'ml', 'unit'),
  ('Fresh Milk 1L', 'Fresh Milk', 1, 'l', 'unit'),
  ('Long Life Milk 500ml', 'Long Life Milk', 500, 'ml', 'unit'),
  ('Long Life Milk 1L', 'Long Life Milk', 1, 'l', 'unit'),
  ('Fermented Milk 500ml', 'Fermented Milk', 500, 'ml', 'unit'),
  ('Yoghurt 250ml', 'Yoghurt', 250, 'ml', 'unit'),
  ('Yoghurt 500ml', 'Yoghurt', 500, 'ml', 'unit'),
  ('Margarine 250g', 'Margarine', 250, 'g', 'unit'),
  ('Margarine 500g', 'Margarine', 500, 'g', 'unit'),
  ('Milk Powder 250g', 'Milk Powder', 250, 'g', 'unit'),
  ('Bread 400g', 'Bread', 400, 'g', 'unit'),
  ('Bread 800g', 'Bread', 800, 'g', 'unit'),
  ('Brown Bread 400g', 'Brown Bread', 400, 'g', 'unit'),
  ('Mandazi', 'Mandazi', NULL, NULL, 'unit'),
  ('Chapati', 'Chapati', NULL, NULL, 'unit'),
  ('Buns', 'Buns', NULL, NULL, 'unit'),
  ('Scones', 'Scones', NULL, NULL, 'unit'),
  ('Doughnuts', 'Doughnuts', NULL, NULL, 'unit'),
  ('Queen Cakes', 'Queen Cakes', NULL, NULL, 'unit'),
  ('Birthday Cake', 'Birthday Cake', NULL, NULL, 'unit'),
  ('Cake Slice', 'Cake Slice', NULL, NULL, 'unit'),
  ('Cookies', 'Cookies', NULL, NULL, 'unit'),
  ('Soda 300ml', 'Soda', 300, 'ml', 'unit'),
  ('Soda 500ml', 'Soda', 500, 'ml', 'unit'),
  ('Soda 1L', 'Soda', 1, 'l', 'unit'),
  ('Soda 2L', 'Soda', 2, 'l', 'unit'),
  ('Bottled Water 500ml', 'Bottled Water', 500, 'ml', 'unit'),
  ('Bottled Water 1L', 'Bottled Water', 1, 'l', 'unit'),
  ('Bottled Water 5L', 'Bottled Water', 5, 'l', 'unit'),
  ('Bottled Water 20L', 'Bottled Water', 20, 'l', 'unit'),
  ('Juice 250ml', 'Juice', 250, 'ml', 'unit'),
  ('Juice 500ml', 'Juice', 500, 'ml', 'unit'),
  ('Juice 1L', 'Juice', 1, 'l', 'unit'),
  ('Tea Leaves 100g', 'Tea Leaves', 100, 'g', 'unit'),
  ('Tea Leaves 250g', 'Tea Leaves', 250, 'g', 'unit'),
  ('Tea Leaves 500g', 'Tea Leaves', 500, 'g', 'unit'),
  ('Coffee 100g', 'Coffee', 100, 'g', 'unit'),
  ('Drinking Chocolate 200g', 'Drinking Chocolate', 200, 'g', 'unit'),
  ('Energy Drink 300ml', 'Energy Drink', 300, 'ml', 'unit'),
  ('Beer 500ml', 'Beer', 500, 'ml', 'unit'),
  ('Beer 330ml', 'Beer', 330, 'ml', 'unit'),
  ('Cider 500ml', 'Cider', 500, 'ml', 'unit'),
  ('Wine 750ml', 'Wine', 750, 'ml', 'unit'),
  ('Wine 375ml', 'Wine', 375, 'ml', 'unit'),
  ('Whisky 250ml', 'Whisky', 250, 'ml', 'unit'),
  ('Whisky 750ml', 'Whisky', 750, 'ml', 'unit'),
  ('Vodka 250ml', 'Vodka', 250, 'ml', 'unit'),
  ('Vodka 750ml', 'Vodka', 750, 'ml', 'unit'),
  ('Gin 750ml', 'Gin', 750, 'ml', 'unit'),
  ('Brandy 750ml', 'Brandy', 750, 'ml', 'unit'),
  ('Rum 750ml', 'Rum', 750, 'ml', 'unit'),
  ('Spirits 250ml', 'Spirits', 250, 'ml', 'unit'),
  ('Keg Beer', 'Keg Beer', NULL, NULL, 'unit'),
  ('Shot', 'Shot', NULL, NULL, 'service'),
  ('Bar Soap 800g', 'Bar Soap', 800, 'g', 'unit'),
  ('Bar Soap 1kg', 'Bar Soap', 1, 'kg', 'unit'),
  ('Washing Powder 500g', 'Washing Powder', 500, 'g', 'unit'),
  ('Washing Powder 1kg', 'Washing Powder', 1, 'kg', 'unit'),
  ('Dishwashing Liquid 500ml', 'Dishwashing Liquid', 500, 'ml', 'unit'),
  ('Dishwashing Bar', 'Dishwashing Bar', NULL, NULL, 'unit'),
  ('Bleach 500ml', 'Bleach', 500, 'ml', 'unit'),
  ('Bleach 750ml', 'Bleach', 750, 'ml', 'unit'),
  ('Steel Wool', 'Steel Wool', NULL, NULL, 'unit'),
  ('Matches', 'Matches', NULL, NULL, 'unit'),
  ('Candles', 'Candles', NULL, NULL, 'unit'),
  ('Toilet Paper Roll', 'Toilet Paper Roll', NULL, NULL, 'unit'),
  ('Toilet Paper 4 Pack', 'Toilet Paper', 4, 'pack', 'unit'),
  ('Toilet Paper 10 Pack', 'Toilet Paper', 10, 'pack', 'unit'),
  ('Tissue Box', 'Tissue Box', NULL, NULL, 'unit'),
  ('Paraffin 1L', 'Paraffin', 1, 'l', 'unit'),
  ('Charcoal 1kg', 'Charcoal', 1, 'kg', 'unit'),
  ('Charcoal Sack', 'Charcoal Sack', NULL, NULL, 'unit'),
  ('Insecticide Spray', 'Insecticide Spray', NULL, NULL, 'unit'),
  ('Toothpaste 50ml', 'Toothpaste', 50, 'ml', 'unit'),
  ('Toothpaste 100ml', 'Toothpaste', 100, 'ml', 'unit'),
  ('Toothbrush', 'Toothbrush', NULL, NULL, 'unit'),
  ('Petroleum Jelly 100g', 'Petroleum Jelly', 100, 'g', 'unit'),
  ('Petroleum Jelly 250g', 'Petroleum Jelly', 250, 'g', 'unit'),
  ('Body Lotion 200ml', 'Body Lotion', 200, 'ml', 'unit'),
  ('Body Lotion 400ml', 'Body Lotion', 400, 'ml', 'unit'),
  ('Bathing Soap', 'Bathing Soap', NULL, NULL, 'unit'),
  ('Shampoo 200ml', 'Shampoo', 200, 'ml', 'unit'),
  ('Sanitary Pads', 'Sanitary Pads', NULL, NULL, 'unit'),
  ('Razor Blades', 'Razor Blades', NULL, NULL, 'unit'),
  ('Roll On Deodorant', 'Roll On Deodorant', NULL, NULL, 'unit'),
  ('Biscuits Small', 'Biscuits Small', NULL, NULL, 'unit'),
  ('Biscuits Family Pack', 'Biscuits Family Pack', NULL, NULL, 'unit'),
  ('Crisps 50g', 'Crisps', 50, 'g', 'unit'),
  ('Sweets', 'Sweets', NULL, NULL, 'unit'),
  ('Chewing Gum', 'Chewing Gum', NULL, NULL, 'unit'),
  ('Groundnuts 100g', 'Groundnuts', 100, 'g', 'unit'),
  ('Popcorn', 'Popcorn', NULL, NULL, 'unit'),
  ('Tomato Paste 50g', 'Tomato Paste', 50, 'g', 'unit'),
  ('Tomato Paste 400g', 'Tomato Paste', 400, 'g', 'unit'),
  ('Tomato Sauce 400ml', 'Tomato Sauce', 400, 'ml', 'unit'),
  ('Curry Powder 100g', 'Curry Powder', 100, 'g', 'unit'),
  ('Stock Cubes', 'Stock Cubes', NULL, NULL, 'unit'),
  ('Black Pepper 50g', 'Black Pepper', 50, 'g', 'unit'),
  ('Chilli Powder 50g', 'Chilli Powder', 50, 'g', 'unit'),
  ('Vinegar 500ml', 'Vinegar', 500, 'ml', 'unit'),
  ('Baking Powder 100g', 'Baking Powder', 100, 'g', 'unit'),
  ('Yeast 50g', 'Yeast', 50, 'g', 'unit'),
  ('Baby Diapers Small Pack', 'Baby Diapers Small Pack', NULL, NULL, 'unit'),
  ('Baby Wipes', 'Baby Wipes', NULL, NULL, 'unit'),
  ('Baby Cereal 400g', 'Baby Cereal', 400, 'g', 'unit'),
  ('Eggs Single', 'Eggs Single', NULL, NULL, 'unit'),
  ('Eggs Tray', 'Eggs Tray', NULL, NULL, 'unit'),
  ('Airtime', 'Airtime', NULL, NULL, 'unit'),
  ('Cigarettes Single', 'Cigarettes Single', NULL, NULL, 'unit'),
  ('Cigarettes Packet', 'Cigarettes Packet', NULL, NULL, 'unit'),
  ('Batteries AA', 'Batteries AA', NULL, NULL, 'unit'),
  ('Batteries D', 'Batteries D', NULL, NULL, 'unit'),
  ('Sukuma Wiki', 'Sukuma Wiki', NULL, NULL, 'unit'),
  ('Spinach', 'Spinach', NULL, NULL, 'unit'),
  ('Cabbage', 'Cabbage', NULL, NULL, 'unit'),
  ('Tomatoes', 'Tomatoes', NULL, NULL, 'weight'),
  ('Onions', 'Onions', NULL, NULL, 'weight'),
  ('Potatoes', 'Potatoes', NULL, NULL, 'weight'),
  ('Carrots', 'Carrots', NULL, NULL, 'weight'),
  ('Dhania', 'Dhania', NULL, NULL, 'unit'),
  ('Capsicum', 'Capsicum', NULL, NULL, 'unit'),
  ('Garlic', 'Garlic', NULL, NULL, 'unit'),
  ('Ginger', 'Ginger', NULL, NULL, 'weight'),
  ('Managu', 'Managu', NULL, NULL, 'unit'),
  ('Terere', 'Terere', NULL, NULL, 'unit'),
  ('Kunde', 'Kunde', NULL, NULL, 'unit'),
  ('Pumpkin', 'Pumpkin', NULL, NULL, 'unit'),
  ('Butternut', 'Butternut', NULL, NULL, 'unit'),
  ('Cucumber', 'Cucumber', NULL, NULL, 'unit'),
  ('Courgette', 'Courgette', NULL, NULL, 'weight'),
  ('French Beans', 'French Beans', NULL, NULL, 'weight'),
  ('Sweet Potatoes', 'Sweet Potatoes', NULL, NULL, 'weight'),
  ('Arrow Roots', 'Arrow Roots', NULL, NULL, 'weight'),
  ('Cassava', 'Cassava', NULL, NULL, 'weight'),
  ('Green Maize', 'Green Maize', NULL, NULL, 'unit'),
  ('Cooking Bananas', 'Cooking Bananas', NULL, NULL, 'unit'),
  ('Bananas', 'Bananas', NULL, NULL, 'unit'),
  ('Mangoes', 'Mangoes', NULL, NULL, 'unit'),
  ('Oranges', 'Oranges', NULL, NULL, 'unit'),
  ('Pineapple', 'Pineapple', NULL, NULL, 'unit'),
  ('Watermelon', 'Watermelon', NULL, NULL, 'unit'),
  ('Apples', 'Apples', NULL, NULL, 'unit'),
  ('Passion Fruit', 'Passion Fruit', NULL, NULL, 'weight'),
  ('Avocado', 'Avocado', NULL, NULL, 'unit'),
  ('Pawpaw', 'Pawpaw', NULL, NULL, 'unit'),
  ('Lemons', 'Lemons', NULL, NULL, 'unit'),
  ('Tree Tomato', 'Tree Tomato', NULL, NULL, 'unit'),
  ('Guava', 'Guava', NULL, NULL, 'unit'),
  ('Grapes', 'Grapes', NULL, NULL, 'weight'),
  ('Plums', 'Plums', NULL, NULL, 'weight'),
  ('Beef', 'Beef', NULL, NULL, 'weight'),
  ('Goat Meat', 'Goat Meat', NULL, NULL, 'weight'),
  ('Mutton', 'Mutton', NULL, NULL, 'weight'),
  ('Pork', 'Pork', NULL, NULL, 'weight'),
  ('Chicken Whole', 'Chicken Whole', NULL, NULL, 'unit'),
  ('Chicken Pieces', 'Chicken Pieces', NULL, NULL, 'weight'),
  ('Minced Meat', 'Minced Meat', NULL, NULL, 'weight'),
  ('Liver', 'Liver', NULL, NULL, 'weight'),
  ('Matumbo', 'Matumbo', NULL, NULL, 'weight'),
  ('Bones', 'Bones', NULL, NULL, 'weight'),
  ('Mutura', 'Mutura', NULL, NULL, 'unit'),
  ('Fish', 'Fish', NULL, NULL, 'unit'),
  ('Smokies', 'Smokies', NULL, NULL, 'unit'),
  ('Sausages', 'Sausages', NULL, NULL, 'unit'),
  ('Boiled Eggs', 'Boiled Eggs', NULL, NULL, 'unit'),
  ('Roast Maize', 'Roast Maize', NULL, NULL, 'unit'),
  ('Kachumbari', 'Kachumbari', NULL, NULL, 'unit'),
  ('Nyama Choma', 'Nyama Choma', NULL, NULL, 'weight'),
  ('Roast Chicken', 'Roast Chicken', NULL, NULL, 'unit'),
  ('Samosa', 'Samosa', NULL, NULL, 'unit'),
  ('Ugali', 'Ugali', NULL, NULL, 'unit'),
  ('Rice Portion', 'Rice Portion', NULL, NULL, 'unit'),
  ('Pilau', 'Pilau', NULL, NULL, 'unit'),
  ('Githeri', 'Githeri', NULL, NULL, 'unit'),
  ('Beans Stew', 'Beans Stew', NULL, NULL, 'unit'),
  ('Beef Stew', 'Beef Stew', NULL, NULL, 'unit'),
  ('Chicken Stew', 'Chicken Stew', NULL, NULL, 'unit'),
  ('Chips', 'Chips', NULL, NULL, 'unit'),
  ('Matoke', 'Matoke', NULL, NULL, 'unit'),
  ('Sukuma Portion', 'Sukuma Portion', NULL, NULL, 'unit'),
  ('Cabbage Portion', 'Cabbage Portion', NULL, NULL, 'unit'),
  ('Tea Cup', 'Tea Cup', NULL, NULL, 'unit'),
  ('Coffee Cup', 'Coffee Cup', NULL, NULL, 'unit'),
  ('Breakfast', 'Breakfast', NULL, NULL, 'unit'),
  ('Lunch', 'Lunch', NULL, NULL, 'unit'),
  ('Paracetamol Tablets', 'Paracetamol Tablets', NULL, NULL, 'unit'),
  ('Ibuprofen Tablets', 'Ibuprofen Tablets', NULL, NULL, 'unit'),
  ('Aspirin Tablets', 'Aspirin Tablets', NULL, NULL, 'unit'),
  ('Antimalarial Tablets', 'Antimalarial Tablets', NULL, NULL, 'unit'),
  ('Amoxicillin Capsules', 'Amoxicillin Capsules', NULL, NULL, 'unit'),
  ('Cough Syrup', 'Cough Syrup', NULL, NULL, 'unit'),
  ('Oral Rehydration Salts', 'Oral Rehydration Salts', NULL, NULL, 'unit'),
  ('Antihistamine Tablets', 'Antihistamine Tablets', NULL, NULL, 'unit'),
  ('Antacid Tablets', 'Antacid Tablets', NULL, NULL, 'unit'),
  ('Deworming Tablets', 'Deworming Tablets', NULL, NULL, 'unit'),
  ('Multivitamins', 'Multivitamins', NULL, NULL, 'unit'),
  ('Eye Drops', 'Eye Drops', NULL, NULL, 'unit'),
  ('Antiseptic Solution', 'Antiseptic Solution', NULL, NULL, 'unit'),
  ('Surgical Spirit', 'Surgical Spirit', NULL, NULL, 'unit'),
  ('Bandage', 'Bandage', NULL, NULL, 'unit'),
  ('Cotton Wool', 'Cotton Wool', NULL, NULL, 'unit'),
  ('Gauze', 'Gauze', NULL, NULL, 'unit'),
  ('Plasters', 'Plasters', NULL, NULL, 'unit'),
  ('Syringe', 'Syringe', NULL, NULL, 'unit'),
  ('Gloves', 'Gloves', NULL, NULL, 'unit'),
  ('Face Mask', 'Face Mask', NULL, NULL, 'unit'),
  ('Thermometer', 'Thermometer', NULL, NULL, 'unit'),
  ('Pregnancy Test Kit', 'Pregnancy Test Kit', NULL, NULL, 'unit'),
  ('Condoms', 'Condoms', NULL, NULL, 'unit'),
  ('Hand Sanitizer', 'Hand Sanitizer', NULL, NULL, 'unit'),
  ('First Aid Kit', 'First Aid Kit', NULL, NULL, 'unit'),
  ('Blood Pressure Check', 'Blood Pressure Check', NULL, NULL, 'service'),
  ('Injection', 'Injection', NULL, NULL, 'service'),
  ('Consultation', 'Consultation', NULL, NULL, 'service'),
  ('Dairy Meal 70kg', 'Dairy Meal', 70, 'kg', 'unit'),
  ('Layers Mash 70kg', 'Layers Mash', 70, 'kg', 'unit'),
  ('Chick Mash 20kg', 'Chick Mash', 20, 'kg', 'unit'),
  ('Growers Mash 50kg', 'Growers Mash', 50, 'kg', 'unit'),
  ('Pig Feed 50kg', 'Pig Feed', 50, 'kg', 'unit'),
  ('Mineral Salts', 'Mineral Salts', NULL, NULL, 'weight'),
  ('Dewormer', 'Dewormer', NULL, NULL, 'unit'),
  ('Acaricide', 'Acaricide', NULL, NULL, 'unit'),
  ('Animal Vaccine', 'Animal Vaccine', NULL, NULL, 'unit'),
  ('Maize Seed 2kg', 'Maize Seed', 2, 'kg', 'unit'),
  ('Bean Seed 2kg', 'Bean Seed', 2, 'kg', 'unit'),
  ('Vegetable Seeds', 'Vegetable Seeds', NULL, NULL, 'unit'),
  ('DAP Fertiliser 50kg', 'DAP Fertiliser', 50, 'kg', 'unit'),
  ('CAN Fertiliser 50kg', 'CAN Fertiliser', 50, 'kg', 'unit'),
  ('NPK Fertiliser 50kg', 'NPK Fertiliser', 50, 'kg', 'unit'),
  ('Pesticide', 'Pesticide', NULL, NULL, 'unit'),
  ('Herbicide', 'Herbicide', NULL, NULL, 'unit'),
  ('Braiding', 'Braiding', NULL, NULL, 'service'),
  ('Weaving', 'Weaving', NULL, NULL, 'service'),
  ('Cornrows', 'Cornrows', NULL, NULL, 'service'),
  ('Twists', 'Twists', NULL, NULL, 'service'),
  ('Dreadlocks', 'Dreadlocks', NULL, NULL, 'service'),
  ('Wash and Set', 'Wash and Set', NULL, NULL, 'service'),
  ('Blow Dry', 'Blow Dry', NULL, NULL, 'service'),
  ('Relaxer Retouch', 'Relaxer Retouch', NULL, NULL, 'service'),
  ('Hair Treatment', 'Hair Treatment', NULL, NULL, 'service'),
  ('Hair Dye', 'Hair Dye', NULL, NULL, 'service'),
  ('Wig Installation', 'Wig Installation', NULL, NULL, 'service'),
  ('Ladies Haircut', 'Ladies Haircut', NULL, NULL, 'service'),
  ('Haircut', 'Haircut', NULL, NULL, 'service'),
  ('Kids Haircut', 'Kids Haircut', NULL, NULL, 'service'),
  ('Beard Trim', 'Beard Trim', NULL, NULL, 'service'),
  ('Lining', 'Lining', NULL, NULL, 'service'),
  ('Head Wash', 'Head Wash', NULL, NULL, 'service'),
  ('Head Massage', 'Head Massage', NULL, NULL, 'service'),
  ('Manicure', 'Manicure', NULL, NULL, 'service'),
  ('Pedicure', 'Pedicure', NULL, NULL, 'service'),
  ('Gel Nails', 'Gel Nails', NULL, NULL, 'service'),
  ('Acrylic Nails', 'Acrylic Nails', NULL, NULL, 'service'),
  ('Nail Art', 'Nail Art', NULL, NULL, 'service'),
  ('Polish Change', 'Polish Change', NULL, NULL, 'service'),
  ('Nail Refill', 'Nail Refill', NULL, NULL, 'service'),
  ('Braids Packet', 'Braids Packet', NULL, NULL, 'unit'),
  ('Weave', 'Weave', NULL, NULL, 'unit'),
  ('Wig', 'Wig', NULL, NULL, 'unit'),
  ('Hair Food', 'Hair Food', NULL, NULL, 'unit'),
  ('Relaxer Kit', 'Relaxer Kit', NULL, NULL, 'unit'),
  ('Hair Conditioner', 'Hair Conditioner', NULL, NULL, 'unit'),
  ('Hair Oil', 'Hair Oil', NULL, NULL, 'unit'),
  ('Comb', 'Comb', NULL, NULL, 'unit'),
  ('Hair Brush', 'Hair Brush', NULL, NULL, 'unit'),
  ('Hair Pins', 'Hair Pins', NULL, NULL, 'unit'),
  ('Nail Polish', 'Nail Polish', NULL, NULL, 'unit'),
  ('Lipstick', 'Lipstick', NULL, NULL, 'unit'),
  ('Foundation', 'Foundation', NULL, NULL, 'unit'),
  ('Face Powder', 'Face Powder', NULL, NULL, 'unit'),
  ('Mascara', 'Mascara', NULL, NULL, 'unit'),
  ('Eyeliner', 'Eyeliner', NULL, NULL, 'unit'),
  ('False Lashes', 'False Lashes', NULL, NULL, 'unit'),
  ('Makeup Brushes', 'Makeup Brushes', NULL, NULL, 'unit'),
  ('Perfume', 'Perfume', NULL, NULL, 'unit'),
  ('Body Spray', 'Body Spray', NULL, NULL, 'unit'),
  ('Cement 50kg', 'Cement', 50, 'kg', 'unit'),
  ('Nails 1kg', 'Nails', 1, 'kg', 'unit'),
  ('Roofing Nails 1kg', 'Roofing Nails', 1, 'kg', 'unit'),
  ('Iron Sheet', 'Iron Sheet', NULL, NULL, 'unit'),
  ('Timber', 'Timber', NULL, NULL, 'unit'),
  ('Sand', 'Sand', NULL, NULL, 'weight'),
  ('Ballast', 'Ballast', NULL, NULL, 'weight'),
  ('Binding Wire 1kg', 'Binding Wire', 1, 'kg', 'unit'),
  ('Paint 1L', 'Paint', 1, 'l', 'unit'),
  ('Paint 4L', 'Paint', 4, 'l', 'unit'),
  ('Paint Brush', 'Paint Brush', NULL, NULL, 'unit'),
  ('PVC Pipe', 'PVC Pipe', NULL, NULL, 'unit'),
  ('Tap', 'Tap', NULL, NULL, 'unit'),
  ('Elbow Joint', 'Elbow Joint', NULL, NULL, 'unit'),
  ('Electric Cable', 'Electric Cable', NULL, NULL, 'length'),
  ('Socket', 'Socket', NULL, NULL, 'unit'),
  ('Switch', 'Switch', NULL, NULL, 'unit'),
  ('Light Bulb', 'Light Bulb', NULL, NULL, 'unit'),
  ('Padlock', 'Padlock', NULL, NULL, 'unit'),
  ('Hammer', 'Hammer', NULL, NULL, 'unit'),
  ('Pliers', 'Pliers', NULL, NULL, 'unit'),
  ('Screwdriver', 'Screwdriver', NULL, NULL, 'unit'),
  ('Tape Measure', 'Tape Measure', NULL, NULL, 'unit'),
  ('Spade', 'Spade', NULL, NULL, 'unit'),
  ('Jembe', 'Jembe', NULL, NULL, 'unit'),
  ('Panga', 'Panga', NULL, NULL, 'unit'),
  ('Wheelbarrow', 'Wheelbarrow', NULL, NULL, 'unit'),
  ('Grinding Disc', 'Grinding Disc', NULL, NULL, 'unit'),
  ('Welding Rods', 'Welding Rods', NULL, NULL, 'unit'),
  ('Sandpaper', 'Sandpaper', NULL, NULL, 'unit'),
  ('Silicone Sealant', 'Silicone Sealant', NULL, NULL, 'unit'),
  ('Hinges', 'Hinges', NULL, NULL, 'unit'),
  ('Door Handle', 'Door Handle', NULL, NULL, 'unit'),
  ('Screws', 'Screws', NULL, NULL, 'unit'),
  ('Wood Glue', 'Wood Glue', NULL, NULL, 'unit'),
  ('Varnish', 'Varnish', NULL, NULL, 'unit'),
  ('Drawer Runners', 'Drawer Runners', NULL, NULL, 'unit'),
  ('Castor Wheels', 'Castor Wheels', NULL, NULL, 'unit'),
  ('Upholstery Foam', 'Upholstery Foam', NULL, NULL, 'unit'),
  ('Upholstery Fabric', 'Upholstery Fabric', NULL, NULL, 'length'),
  ('Wood Polish', 'Wood Polish', NULL, NULL, 'unit'),
  ('Bucket', 'Bucket', NULL, NULL, 'unit'),
  ('Basin', 'Basin', NULL, NULL, 'unit'),
  ('Jug', 'Jug', NULL, NULL, 'unit'),
  ('Cups', 'Cups', NULL, NULL, 'unit'),
  ('Plates', 'Plates', NULL, NULL, 'unit'),
  ('Glasses', 'Glasses', NULL, NULL, 'unit'),
  ('Sufuria', 'Sufuria', NULL, NULL, 'unit'),
  ('Frying Pan', 'Frying Pan', NULL, NULL, 'unit'),
  ('Kettle', 'Kettle', NULL, NULL, 'unit'),
  ('Thermos Flask', 'Thermos Flask', NULL, NULL, 'unit'),
  ('Cutlery Set', 'Cutlery Set', NULL, NULL, 'unit'),
  ('Kitchen Knife', 'Kitchen Knife', NULL, NULL, 'unit'),
  ('Chopping Board', 'Chopping Board', NULL, NULL, 'unit'),
  ('Mop', 'Mop', NULL, NULL, 'unit'),
  ('Broom', 'Broom', NULL, NULL, 'unit'),
  ('Dustpan', 'Dustpan', NULL, NULL, 'unit'),
  ('Clothes Hangers', 'Clothes Hangers', NULL, NULL, 'unit'),
  ('Laundry Basket', 'Laundry Basket', NULL, NULL, 'unit'),
  ('Dustbin', 'Dustbin', NULL, NULL, 'unit'),
  ('Door Mat', 'Door Mat', NULL, NULL, 'unit'),
  ('Curtains', 'Curtains', NULL, NULL, 'unit'),
  ('Bedsheets', 'Bedsheets', NULL, NULL, 'unit'),
  ('Blanket', 'Blanket', NULL, NULL, 'unit'),
  ('Towel', 'Towel', NULL, NULL, 'unit'),
  ('Pillow', 'Pillow', NULL, NULL, 'unit'),
  ('Jiko', 'Jiko', NULL, NULL, 'unit'),
  ('Gas Burner', 'Gas Burner', NULL, NULL, 'unit'),
  ('Water Dispenser', 'Water Dispenser', NULL, NULL, 'unit'),
  ('Storage Container', 'Storage Container', NULL, NULL, 'unit'),
  ('Jerrycan', 'Jerrycan', NULL, NULL, 'unit'),
  ('Exercise Book', 'Exercise Book', NULL, NULL, 'unit'),
  ('Counter Book', 'Counter Book', NULL, NULL, 'unit'),
  ('Graph Book', 'Graph Book', NULL, NULL, 'unit'),
  ('Textbook', 'Textbook', NULL, NULL, 'unit'),
  ('Pen', 'Pen', NULL, NULL, 'unit'),
  ('Pencil', 'Pencil', NULL, NULL, 'unit'),
  ('Ruler', 'Ruler', NULL, NULL, 'unit'),
  ('Eraser', 'Eraser', NULL, NULL, 'unit'),
  ('Sharpener', 'Sharpener', NULL, NULL, 'unit'),
  ('Geometry Set', 'Geometry Set', NULL, NULL, 'unit'),
  ('Crayons', 'Crayons', NULL, NULL, 'unit'),
  ('Coloured Pencils', 'Coloured Pencils', NULL, NULL, 'unit'),
  ('Manila Paper', 'Manila Paper', NULL, NULL, 'unit'),
  ('Printing Paper Ream', 'Printing Paper Ream', NULL, NULL, 'unit'),
  ('Glue Stick', 'Glue Stick', NULL, NULL, 'unit'),
  ('Stapler', 'Stapler', NULL, NULL, 'unit'),
  ('Staples', 'Staples', NULL, NULL, 'unit'),
  ('File', 'File', NULL, NULL, 'unit'),
  ('Envelope', 'Envelope', NULL, NULL, 'unit'),
  ('Calculator', 'Calculator', NULL, NULL, 'unit'),
  ('School Bag', 'School Bag', NULL, NULL, 'unit'),
  ('Chalk', 'Chalk', NULL, NULL, 'unit'),
  ('Whiteboard Marker', 'Whiteboard Marker', NULL, NULL, 'unit'),
  ('Receipt Book', 'Receipt Book', NULL, NULL, 'unit'),
  ('Printing Black and White', 'Printing Black and White', NULL, NULL, 'service'),
  ('Printing Colour', 'Printing Colour', NULL, NULL, 'service'),
  ('Photocopy', 'Photocopy', NULL, NULL, 'service'),
  ('Lamination', 'Lamination', NULL, NULL, 'service'),
  ('Scanning', 'Scanning', NULL, NULL, 'service'),
  ('Typing', 'Typing', NULL, NULL, 'service'),
  ('Binding', 'Binding', NULL, NULL, 'service'),
  ('Passport Photos', 'Passport Photos', NULL, NULL, 'service'),
  ('Internet Browsing', 'Internet Browsing', NULL, NULL, 'service'),
  ('CV Writing', 'CV Writing', NULL, NULL, 'service'),
  ('eCitizen Services', 'eCitizen Services', NULL, NULL, 'service'),
  ('KRA Services', 'KRA Services', NULL, NULL, 'service'),
  ('Phone Charger', 'Phone Charger', NULL, NULL, 'unit'),
  ('Earphones', 'Earphones', NULL, NULL, 'unit'),
  ('Headphones', 'Headphones', NULL, NULL, 'unit'),
  ('Screen Protector', 'Screen Protector', NULL, NULL, 'unit'),
  ('Phone Case', 'Phone Case', NULL, NULL, 'unit'),
  ('Memory Card', 'Memory Card', NULL, NULL, 'unit'),
  ('Flash Disk', 'Flash Disk', NULL, NULL, 'unit'),
  ('Power Bank', 'Power Bank', NULL, NULL, 'unit'),
  ('USB Cable', 'USB Cable', NULL, NULL, 'unit'),
  ('Extension Cable', 'Extension Cable', NULL, NULL, 'unit'),
  ('Radio', 'Radio', NULL, NULL, 'unit'),
  ('Bluetooth Speaker', 'Bluetooth Speaker', NULL, NULL, 'unit'),
  ('TV Aerial', 'TV Aerial', NULL, NULL, 'unit'),
  ('Sim Card', 'Sim Card', NULL, NULL, 'unit'),
  ('Phone Adapter', 'Phone Adapter', NULL, NULL, 'unit'),
  ('Screen Replacement', 'Screen Replacement', NULL, NULL, 'service'),
  ('Battery Replacement', 'Battery Replacement', NULL, NULL, 'service'),
  ('Charging Port Repair', 'Charging Port Repair', NULL, NULL, 'service'),
  ('Software Update', 'Software Update', NULL, NULL, 'service'),
  ('Phone Unlocking', 'Phone Unlocking', NULL, NULL, 'service'),
  ('Phone Diagnostics', 'Phone Diagnostics', NULL, NULL, 'service'),
  ('Phone Charging', 'Phone Charging', NULL, NULL, 'service'),
  ('Seedlings', 'Seedlings', NULL, NULL, 'unit'),
  ('Potted Plant', 'Potted Plant', NULL, NULL, 'unit'),
  ('Flower Pot', 'Flower Pot', NULL, NULL, 'unit'),
  ('Garden Soil', 'Garden Soil', NULL, NULL, 'unit'),
  ('Manure', 'Manure', NULL, NULL, 'unit'),
  ('Ornamental Plant', 'Ornamental Plant', NULL, NULL, 'unit'),
  ('Grass Sod', 'Grass Sod', NULL, NULL, 'area'),
  ('Watering Can', 'Watering Can', NULL, NULL, 'unit'),
  ('Pruning Shears', 'Pruning Shears', NULL, NULL, 'unit'),
  ('Plant Food', 'Plant Food', NULL, NULL, 'unit'),
  ('Water Refill 10L', 'Water Refill', 10, 'l', 'unit'),
  ('Water Refill 20L', 'Water Refill', 20, 'l', 'unit'),
  ('Water Refill 5L', 'Water Refill', 5, 'l', 'unit'),
  ('Dispenser Bottle', 'Dispenser Bottle', NULL, NULL, 'unit'),
  ('Water Delivery', 'Water Delivery', NULL, NULL, 'service'),
  ('Maize Grain 1kg', 'Maize Grain', 1, 'kg', 'unit'),
  ('Maize Grain 90kg', 'Maize Grain', 90, 'kg', 'unit'),
  ('Millet 1kg', 'Millet', 1, 'kg', 'unit'),
  ('Sorghum 1kg', 'Sorghum', 1, 'kg', 'unit'),
  ('Cowpeas 1kg', 'Cowpeas', 1, 'kg', 'unit'),
  ('Njahi 1kg', 'Njahi', 1, 'kg', 'unit'),
  ('Sunflower Seed 1kg', 'Sunflower Seed', 1, 'kg', 'unit'),
  ('Groundnuts 1kg', 'Groundnuts', 1, 'kg', 'unit'),
  ('Milling per Kg', 'Milling per Kg', NULL, NULL, 'service'),
  ('Milling per Debe', 'Milling per Debe', NULL, NULL, 'service'),
  ('Cash Deposit', 'Cash Deposit', NULL, NULL, 'service'),
  ('Cash Withdrawal', 'Cash Withdrawal', NULL, NULL, 'service'),
  ('Bill Payment', 'Bill Payment', NULL, NULL, 'service'),
  ('Car Wash Saloon', 'Car Wash Saloon', NULL, NULL, 'service'),
  ('Car Wash SUV', 'Car Wash SUV', NULL, NULL, 'service'),
  ('Motorbike Wash', 'Motorbike Wash', NULL, NULL, 'service'),
  ('Interior Cleaning', 'Interior Cleaning', NULL, NULL, 'service'),
  ('Engine Wash', 'Engine Wash', NULL, NULL, 'service'),
  ('Waxing', 'Waxing', NULL, NULL, 'service'),
  ('Washing per Kg', 'Washing per Kg', NULL, NULL, 'service'),
  ('Dry Cleaning', 'Dry Cleaning', NULL, NULL, 'service'),
  ('Ironing', 'Ironing', NULL, NULL, 'service'),
  ('Duvet Cleaning', 'Duvet Cleaning', NULL, NULL, 'service'),
  ('Suit Cleaning', 'Suit Cleaning', NULL, NULL, 'service'),
  ('Thread', 'Thread', NULL, NULL, 'unit'),
  ('Zip', 'Zip', NULL, NULL, 'unit'),
  ('Buttons', 'Buttons', NULL, NULL, 'unit'),
  ('Fabric', 'Fabric', NULL, NULL, 'length'),
  ('Elastic', 'Elastic', NULL, NULL, 'length'),
  ('Needles', 'Needles', NULL, NULL, 'unit'),
  ('Dress Making', 'Dress Making', NULL, NULL, 'service'),
  ('Alteration', 'Alteration', NULL, NULL, 'service'),
  ('Hemming', 'Hemming', NULL, NULL, 'service'),
  ('Clothes Repair', 'Clothes Repair', NULL, NULL, 'service'),
  ('School Uniform', 'School Uniform', NULL, NULL, 'service'),
  ('Shirt', 'Shirt', NULL, NULL, 'unit'),
  ('Trousers', 'Trousers', NULL, NULL, 'unit'),
  ('Dress', 'Dress', NULL, NULL, 'unit'),
  ('Skirt', 'Skirt', NULL, NULL, 'unit'),
  ('T Shirt', 'T Shirt', NULL, NULL, 'unit'),
  ('Jeans', 'Jeans', NULL, NULL, 'unit'),
  ('Jacket', 'Jacket', NULL, NULL, 'unit'),
  ('Sweater', 'Sweater', NULL, NULL, 'unit'),
  ('Socks', 'Socks', NULL, NULL, 'unit'),
  ('Underwear', 'Underwear', NULL, NULL, 'unit'),
  ('Bra', 'Bra', NULL, NULL, 'unit'),
  ('Childrens Clothes', 'Childrens Clothes', NULL, NULL, 'unit'),
  ('School Uniform Set', 'School Uniform Set', NULL, NULL, 'unit'),
  ('Shoes Mens', 'Shoes Mens', NULL, NULL, 'unit'),
  ('Shoes Ladies', 'Shoes Ladies', NULL, NULL, 'unit'),
  ('School Shoes', 'School Shoes', NULL, NULL, 'unit'),
  ('Sandals', 'Sandals', NULL, NULL, 'unit'),
  ('Slippers', 'Slippers', NULL, NULL, 'unit'),
  ('Sports Shoes', 'Sports Shoes', NULL, NULL, 'unit'),
  ('Boots', 'Boots', NULL, NULL, 'unit'),
  ('Shoe Polish', 'Shoe Polish', NULL, NULL, 'unit'),
  ('Shoe Laces', 'Shoe Laces', NULL, NULL, 'unit'),
  ('Cooking Gas Refill 6kg', 'Cooking Gas Refill', 6, 'kg', 'unit'),
  ('Cooking Gas Refill 13kg', 'Cooking Gas Refill', 13, 'kg', 'unit'),
  ('Gas Cylinder 6kg', 'Gas Cylinder', 6, 'kg', 'unit'),
  ('Gas Regulator', 'Gas Regulator', NULL, NULL, 'unit'),
  ('Gas Pipe', 'Gas Pipe', NULL, NULL, 'unit'),
  ('Gas Grill', 'Gas Grill', NULL, NULL, 'unit'),
  ('Day Old Chicks', 'Day Old Chicks', NULL, NULL, 'unit'),
  ('Kienyeji Chicken', 'Kienyeji Chicken', NULL, NULL, 'unit'),
  ('Broiler Chicken', 'Broiler Chicken', NULL, NULL, 'unit')
) AS v(name, product_type, size_value, size_unit, sold_by)
WHERE c.name = v.name;

-- Anything unmatched still needs a type, since it is what grouping keys on.
UPDATE public.canonical_products SET product_type = name WHERE product_type IS NULL;
ALTER TABLE public.canonical_products ALTER COLUMN product_type SET NOT NULL;

CREATE INDEX IF NOT EXISTS canonical_products_type_brand_idx
  ON public.canonical_products (product_type, brand);

INSERT INTO public.canonical_products
  (name, product_type, brand, size_value, size_unit, sold_by, category, business_types, aliases)
VALUES
  ('Tusker Lager 500ml', 'Beer', 'Tusker Lager', 500, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor', 'restaurant'], ARRAY['tusker', 'tusker 500ml', 'tusker lager']),
  ('Tusker Lager 330ml', 'Beer', 'Tusker Lager', 330, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor', 'restaurant'], ARRAY['tusker', 'tusker 330ml', 'tusker lager']),
  ('Tusker Lite 500ml', 'Beer', 'Tusker Lite', 500, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor', 'restaurant'], ARRAY['lite', 'tusker lite', 'tusker lite 500ml']),
  ('Tusker Lite 330ml', 'Beer', 'Tusker Lite', 330, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor', 'restaurant'], ARRAY['lite', 'tusker lite', 'tusker lite 330ml']),
  ('Tusker Malt 500ml', 'Beer', 'Tusker Malt', 500, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor', 'restaurant'], ARRAY['malt', 'tusker malt', 'tusker malt 500ml']),
  ('Tusker Malt 330ml', 'Beer', 'Tusker Malt', 330, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor', 'restaurant'], ARRAY['malt', 'tusker malt', 'tusker malt 330ml']),
  ('White Cap 500ml', 'Beer', 'White Cap', 500, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor', 'restaurant'], ARRAY['white cap', 'white cap 500ml', 'whitecap', 'whitecup']),
  ('White Cap 330ml', 'Beer', 'White Cap', 330, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor', 'restaurant'], ARRAY['white cap', 'white cap 330ml', 'whitecap', 'whitecup']),
  ('Pilsner 500ml', 'Beer', 'Pilsner', 500, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor', 'restaurant'], ARRAY['pilsner', 'pilsner 500ml', 'pizna']),
  ('Pilsner 330ml', 'Beer', 'Pilsner', 330, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor', 'restaurant'], ARRAY['pilsner', 'pilsner 330ml', 'pizna']),
  ('Guinness 500ml', 'Beer', 'Guinness', 500, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor', 'restaurant'], ARRAY['gini', 'guiness', 'guinness', 'guinness 500ml']),
  ('Guinness 330ml', 'Beer', 'Guinness', 330, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor', 'restaurant'], ARRAY['gini', 'guiness', 'guinness', 'guinness 330ml']),
  ('Balozi 500ml', 'Beer', 'Balozi', 500, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor', 'restaurant'], ARRAY['balozi', 'balozi 500ml']),
  ('Balozi 330ml', 'Beer', 'Balozi', 330, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor', 'restaurant'], ARRAY['balozi', 'balozi 330ml']),
  ('Summit Lager 500ml', 'Beer', 'Summit Lager', 500, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor', 'restaurant'], ARRAY['summit', 'summit 500ml', 'summit lager']),
  ('Summit Lager 330ml', 'Beer', 'Summit Lager', 330, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor', 'restaurant'], ARRAY['summit', 'summit 330ml', 'summit lager']),
  ('Heineken 500ml', 'Beer', 'Heineken', 500, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor', 'restaurant'], ARRAY['heineken', 'heineken 500ml', 'heiny']),
  ('Heineken 330ml', 'Beer', 'Heineken', 330, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor', 'restaurant'], ARRAY['heineken', 'heineken 330ml', 'heiny']),
  ('Faxe 500ml', 'Beer', 'Faxe', 500, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor', 'restaurant'], ARRAY['faxe', 'faxe 500ml']),
  ('Faxe 330ml', 'Beer', 'Faxe', 330, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor', 'restaurant'], ARRAY['faxe', 'faxe 330ml']),
  ('Allsopps 500ml', 'Beer', 'Allsopps', 500, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor', 'restaurant'], ARRAY['allsopps', 'allsopps 500ml', 'allsops']),
  ('Allsopps 330ml', 'Beer', 'Allsopps', 330, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor', 'restaurant'], ARRAY['allsopps', 'allsopps 330ml', 'allsops']),
  ('Senator Keg 300ml', 'Beer', 'Senator Keg', 300, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['keg', 'senator', 'senator 300ml', 'senator keg']),
  ('Tusker Cider 330ml', 'Cider', 'Tusker Cider', 330, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['tusker cider', 'tusker cider 330ml']),
  ('Snapp 330ml', 'Cider', 'Snapp', 330, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['snap', 'snapp', 'snapp 330ml']),
  ('Manyatta 330ml', 'Cider', 'Manyatta', 330, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['manyatta', 'manyatta 330ml']),
  ('Smirnoff Ice 330ml', 'Cider', 'Smirnoff Ice', 330, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['black ice', 'smirnoff ice', 'smirnoff ice 330ml']),
  ('Kenya Cane 250ml', 'Spirits', 'Kenya Cane', 250, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['cane', 'kc', 'kenya cane', 'kenya cane 250ml']),
  ('Kenya Cane 750ml', 'Spirits', 'Kenya Cane', 750, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['cane', 'kc', 'kenya cane', 'kenya cane 750ml']),
  ('Chrome Vodka 250ml', 'Spirits', 'Chrome Vodka', 250, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['chrome', 'chrome 250ml', 'chrome vodka']),
  ('Chrome Vodka 750ml', 'Spirits', 'Chrome Vodka', 750, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['chrome', 'chrome 750ml', 'chrome vodka']),
  ('Chrome Gin 250ml', 'Spirits', 'Chrome Gin', 250, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['chrome gin', 'chrome gin 250ml']),
  ('Chrome Gin 750ml', 'Spirits', 'Chrome Gin', 750, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['chrome gin', 'chrome gin 750ml']),
  ('Gilbeys Gin 250ml', 'Spirits', 'Gilbeys Gin', 250, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['gilbey', 'gilbeys', 'gilbeys 250ml', 'gilbeys gin']),
  ('Gilbeys Gin 750ml', 'Spirits', 'Gilbeys Gin', 750, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['gilbey', 'gilbeys', 'gilbeys 750ml', 'gilbeys gin']),
  ('Smirnoff Vodka 250ml', 'Spirits', 'Smirnoff Vodka', 250, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['smirnoff', 'smirnoff 250ml', 'smirnoff vodka']),
  ('Smirnoff Vodka 750ml', 'Spirits', 'Smirnoff Vodka', 750, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['smirnoff', 'smirnoff 750ml', 'smirnoff vodka']),
  ('Konyagi 250ml', 'Spirits', 'Konyagi', 250, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['konyagi', 'konyagi 250ml']),
  ('Konyagi 750ml', 'Spirits', 'Konyagi', 750, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['konyagi', 'konyagi 750ml']),
  ('Hunters Choice 250ml', 'Spirits', 'Hunters Choice', 250, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['hunters', 'hunters 250ml', 'hunters choice']),
  ('Hunters Choice 750ml', 'Spirits', 'Hunters Choice', 750, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['hunters', 'hunters 750ml', 'hunters choice']),
  ('Best Whisky 250ml', 'Spirits', 'Best Whisky', 250, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['best', 'best whisky', 'best whisky 250ml']),
  ('Best Whisky 750ml', 'Spirits', 'Best Whisky', 750, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['best', 'best whisky', 'best whisky 750ml']),
  ('Best Gin 250ml', 'Spirits', 'Best Gin', 250, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['best gin', 'best gin 250ml']),
  ('Best Gin 750ml', 'Spirits', 'Best Gin', 750, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['best gin', 'best gin 750ml']),
  ('County Vodka 250ml', 'Spirits', 'County Vodka', 250, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['county', 'county 250ml', 'county vodka']),
  ('County Vodka 750ml', 'Spirits', 'County Vodka', 750, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['county', 'county 750ml', 'county vodka']),
  ('Triple Ace 250ml', 'Spirits', 'Triple Ace', 250, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['triple', 'triple ace', 'triple ace 250ml']),
  ('Triple Ace 750ml', 'Spirits', 'Triple Ace', 750, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['triple', 'triple ace', 'triple ace 750ml']),
  ('Kane Extra 250ml', 'Spirits', 'Kane Extra', 250, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['kane', 'kane extra', 'kane extra 250ml']),
  ('Kane Extra 750ml', 'Spirits', 'Kane Extra', 750, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['kane', 'kane extra', 'kane extra 750ml']),
  ('Viceroy 250ml', 'Spirits', 'Viceroy', 250, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['viceroy', 'viceroy 250ml']),
  ('Viceroy 750ml', 'Spirits', 'Viceroy', 750, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['viceroy', 'viceroy 750ml']),
  ('Richot 250ml', 'Spirits', 'Richot', 250, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['richoh', 'richot', 'richot 250ml']),
  ('Richot 750ml', 'Spirits', 'Richot', 750, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['richoh', 'richot', 'richot 750ml']),
  ('Bond 7 250ml', 'Spirits', 'Bond 7', 250, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['bond 7', 'bond 7 250ml', 'bond seven']),
  ('Bond 7 750ml', 'Spirits', 'Bond 7', 750, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['bond 7', 'bond 7 750ml', 'bond seven']),
  ('Johnnie Walker Red 750ml', 'Spirits', 'Johnnie Walker Red', 750, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['johnnie walker', 'johnnie walker 750ml', 'jw red', 'red label']),
  ('Johnnie Walker Black 750ml', 'Spirits', 'Johnnie Walker Black', 750, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['black label', 'black label 750ml', 'jw black']),
  ('Jack Daniels 750ml', 'Spirits', 'Jack Daniels', 750, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['jack', 'jack daniels', 'jack daniels 750ml', 'jd']),
  ('Jameson 750ml', 'Spirits', 'Jameson', 750, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['jameson', 'jameson 750ml']),
  ('Black and White 750ml', 'Spirits', 'Black and White', 750, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['b and w', 'black and white', 'black and white 750ml']),
  ('Famous Grouse 750ml', 'Spirits', 'Famous Grouse', 750, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['famous grouse', 'famous grouse 750ml', 'grouse']),
  ('Captain Morgan 750ml', 'Spirits', 'Captain Morgan', 750, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['captain', 'captain morgan', 'captain morgan 750ml']),
  ('4th Street 750ml', 'Wine', '4th Street', 750, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['4th', '4th street', '4th street 750ml', 'fourth street']),
  ('Caprice 750ml', 'Wine', 'Caprice', 750, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['caprice', 'caprice 750ml']),
  ('Drostdy Hof 750ml', 'Wine', 'Drostdy Hof', 750, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['drostdy', 'drostdy 750ml', 'drostdy hof']),
  ('Nederburg 750ml', 'Wine', 'Nederburg', 750, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['nederburg', 'nederburg 750ml']),
  ('Robertson 750ml', 'Wine', 'Robertson', 750, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['robertson', 'robertson 750ml']),
  ('Cellar Cask 750ml', 'Wine', 'Cellar Cask', 750, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['cellar', 'cellar cask', 'cellar cask 750ml']),
  ('Two Oceans 750ml', 'Wine', 'Two Oceans', 750, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['two oceans', 'two oceans 750ml']),
  ('Overmeer 750ml', 'Wine', 'Overmeer', 750, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['overmeer', 'overmeer 750ml']),
  ('Frontera 750ml', 'Wine', 'Frontera', 750, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['frontera', 'frontera 750ml']),
  ('Baron Romero 750ml', 'Wine', 'Baron Romero', 750, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['baron', 'baron romero', 'baron romero 750ml']),
  ('4th Street 1l', 'Wine', '4th Street', 1, 'l', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['4th street 1 litre', '4th street 1 litre 1l']),
  ('Amarula 750ml', 'Cream Liqueur', 'Amarula', 750, 'ml', 'unit', 'Alcohol', ARRAY['bar_liquor'], ARRAY['amarula', 'amarula 750ml']),
  ('Coca Cola 300ml', 'Soda', 'Coca Cola', 300, 'ml', 'unit', 'Drinks', ARRAY['bar_liquor', 'duka', 'mini_supermarket', 'restaurant'], ARRAY['coca cola', 'coke', 'coke 300ml', 'cola']),
  ('Coca Cola 500ml', 'Soda', 'Coca Cola', 500, 'ml', 'unit', 'Drinks', ARRAY['bar_liquor', 'duka', 'mini_supermarket', 'restaurant'], ARRAY['coca cola', 'coke', 'coke 500ml', 'cola']),
  ('Fanta Orange 300ml', 'Soda', 'Fanta Orange', 300, 'ml', 'unit', 'Drinks', ARRAY['bar_liquor', 'duka', 'mini_supermarket', 'restaurant'], ARRAY['fanta', 'fanta 300ml', 'fanta orange']),
  ('Fanta Orange 500ml', 'Soda', 'Fanta Orange', 500, 'ml', 'unit', 'Drinks', ARRAY['bar_liquor', 'duka', 'mini_supermarket', 'restaurant'], ARRAY['fanta', 'fanta 500ml', 'fanta orange']),
  ('Fanta Blackcurrant 300ml', 'Soda', 'Fanta Blackcurrant', 300, 'ml', 'unit', 'Drinks', ARRAY['bar_liquor', 'duka', 'mini_supermarket', 'restaurant'], ARRAY['blackcurrant', 'blackcurrant 300ml', 'fanta blackcurrant']),
  ('Fanta Blackcurrant 500ml', 'Soda', 'Fanta Blackcurrant', 500, 'ml', 'unit', 'Drinks', ARRAY['bar_liquor', 'duka', 'mini_supermarket', 'restaurant'], ARRAY['blackcurrant', 'blackcurrant 500ml', 'fanta blackcurrant']),
  ('Fanta Passion 300ml', 'Soda', 'Fanta Passion', 300, 'ml', 'unit', 'Drinks', ARRAY['bar_liquor', 'duka', 'mini_supermarket', 'restaurant'], ARRAY['fanta passion', 'fanta passion 300ml', 'passion soda']),
  ('Fanta Passion 500ml', 'Soda', 'Fanta Passion', 500, 'ml', 'unit', 'Drinks', ARRAY['bar_liquor', 'duka', 'mini_supermarket', 'restaurant'], ARRAY['fanta passion', 'fanta passion 500ml', 'passion soda']),
  ('Sprite 300ml', 'Soda', 'Sprite', 300, 'ml', 'unit', 'Drinks', ARRAY['bar_liquor', 'duka', 'mini_supermarket', 'restaurant'], ARRAY['sprite', 'sprite 300ml']),
  ('Sprite 500ml', 'Soda', 'Sprite', 500, 'ml', 'unit', 'Drinks', ARRAY['bar_liquor', 'duka', 'mini_supermarket', 'restaurant'], ARRAY['sprite', 'sprite 500ml']),
  ('Stoney Tangawizi 300ml', 'Soda', 'Stoney Tangawizi', 300, 'ml', 'unit', 'Drinks', ARRAY['bar_liquor', 'duka', 'mini_supermarket', 'restaurant'], ARRAY['stoney', 'stoney 300ml', 'stoney tangawizi', 'tangawizi']),
  ('Stoney Tangawizi 500ml', 'Soda', 'Stoney Tangawizi', 500, 'ml', 'unit', 'Drinks', ARRAY['bar_liquor', 'duka', 'mini_supermarket', 'restaurant'], ARRAY['stoney', 'stoney 500ml', 'stoney tangawizi', 'tangawizi']),
  ('Krest 300ml', 'Soda', 'Krest', 300, 'ml', 'unit', 'Drinks', ARRAY['bar_liquor', 'duka', 'mini_supermarket', 'restaurant'], ARRAY['bitter lemon', 'krest', 'krest 300ml']),
  ('Krest 500ml', 'Soda', 'Krest', 500, 'ml', 'unit', 'Drinks', ARRAY['bar_liquor', 'duka', 'mini_supermarket', 'restaurant'], ARRAY['bitter lemon', 'krest', 'krest 500ml']),
  ('Schweppes 300ml', 'Soda', 'Schweppes', 300, 'ml', 'unit', 'Drinks', ARRAY['bar_liquor', 'duka', 'mini_supermarket', 'restaurant'], ARRAY['schweppes', 'schweppes 300ml', 'tonic']),
  ('Schweppes 500ml', 'Soda', 'Schweppes', 500, 'ml', 'unit', 'Drinks', ARRAY['bar_liquor', 'duka', 'mini_supermarket', 'restaurant'], ARRAY['schweppes', 'schweppes 500ml', 'tonic']),
  ('Pepsi 300ml', 'Soda', 'Pepsi', 300, 'ml', 'unit', 'Drinks', ARRAY['bar_liquor', 'duka', 'mini_supermarket', 'restaurant'], ARRAY['pepsi', 'pepsi 300ml']),
  ('Pepsi 500ml', 'Soda', 'Pepsi', 500, 'ml', 'unit', 'Drinks', ARRAY['bar_liquor', 'duka', 'mini_supermarket', 'restaurant'], ARRAY['pepsi', 'pepsi 500ml']),
  ('Mirinda 300ml', 'Soda', 'Mirinda', 300, 'ml', 'unit', 'Drinks', ARRAY['bar_liquor', 'duka', 'mini_supermarket', 'restaurant'], ARRAY['mirinda', 'mirinda 300ml']),
  ('Mirinda 500ml', 'Soda', 'Mirinda', 500, 'ml', 'unit', 'Drinks', ARRAY['bar_liquor', 'duka', 'mini_supermarket', 'restaurant'], ARRAY['mirinda', 'mirinda 500ml']),
  ('Mountain Dew 300ml', 'Soda', 'Mountain Dew', 300, 'ml', 'unit', 'Drinks', ARRAY['bar_liquor', 'duka', 'mini_supermarket', 'restaurant'], ARRAY['dew', 'mountain dew', 'mountain dew 300ml']),
  ('Mountain Dew 500ml', 'Soda', 'Mountain Dew', 500, 'ml', 'unit', 'Drinks', ARRAY['bar_liquor', 'duka', 'mini_supermarket', 'restaurant'], ARRAY['dew', 'mountain dew', 'mountain dew 500ml']),
  ('Novida 300ml', 'Soda', 'Novida', 300, 'ml', 'unit', 'Drinks', ARRAY['bar_liquor', 'duka', 'mini_supermarket', 'restaurant'], ARRAY['novida', 'novida 300ml']),
  ('Novida 500ml', 'Soda', 'Novida', 500, 'ml', 'unit', 'Drinks', ARRAY['bar_liquor', 'duka', 'mini_supermarket', 'restaurant'], ARRAY['novida', 'novida 500ml']),
  ('Coca Cola 2l', 'Soda', 'Coca Cola', 2, 'l', 'unit', 'Drinks', ARRAY['bar_liquor', 'duka', 'mini_supermarket', 'restaurant'], ARRAY['coke 2l', 'coke 2l 2l']),
  ('Fanta Orange 2l', 'Soda', 'Fanta Orange', 2, 'l', 'unit', 'Drinks', ARRAY['bar_liquor', 'duka', 'mini_supermarket', 'restaurant'], ARRAY['fanta 2l', 'fanta 2l 2l']),
  ('Sprite 2l', 'Soda', 'Sprite', 2, 'l', 'unit', 'Drinks', ARRAY['bar_liquor', 'duka', 'mini_supermarket', 'restaurant'], ARRAY['sprite 2l', 'sprite 2l 2l']),
  ('Predator 350ml', 'Energy Drink', 'Predator', 350, 'ml', 'unit', 'Drinks', ARRAY['bar_liquor', 'duka', 'mini_supermarket'], ARRAY['predator', 'predator 350ml']),
  ('Power Play 350ml', 'Energy Drink', 'Power Play', 350, 'ml', 'unit', 'Drinks', ARRAY['bar_liquor', 'duka', 'mini_supermarket'], ARRAY['power play', 'power play 350ml']),
  ('Dasani 500ml', 'Bottled Water', 'Dasani', 500, 'ml', 'unit', 'Drinks', ARRAY['duka', 'mini_supermarket'], ARRAY['dasani', 'dasani 500ml']),
  ('Keringet 500ml', 'Bottled Water', 'Keringet', 500, 'ml', 'unit', 'Drinks', ARRAY['duka', 'mini_supermarket'], ARRAY['keringet', 'keringet 500ml']),
  ('Sportsman Single', 'Cigarettes', 'Sportsman', 1, 'stick', 'unit', 'Other', ARRAY['bar_liquor', 'duka', 'mini_supermarket'], ARRAY['sm', 'sportsman', 'sportsman single']),
  ('Sportsman Packet', 'Cigarettes', 'Sportsman', 20, 'stick', 'unit', 'Other', ARRAY['bar_liquor', 'duka', 'mini_supermarket'], ARRAY['sm', 'sportsman', 'sportsman packet']),
  ('Embassy Kings Single', 'Cigarettes', 'Embassy Kings', 1, 'stick', 'unit', 'Other', ARRAY['bar_liquor', 'duka', 'mini_supermarket'], ARRAY['embassy', 'embassy kings', 'embassy single']),
  ('Embassy Kings Packet', 'Cigarettes', 'Embassy Kings', 20, 'stick', 'unit', 'Other', ARRAY['bar_liquor', 'duka', 'mini_supermarket'], ARRAY['embassy', 'embassy kings', 'embassy packet']),
  ('Dunhill Single', 'Cigarettes', 'Dunhill', 1, 'stick', 'unit', 'Other', ARRAY['bar_liquor', 'duka', 'mini_supermarket'], ARRAY['dunhill', 'dunhill single']),
  ('Dunhill Packet', 'Cigarettes', 'Dunhill', 20, 'stick', 'unit', 'Other', ARRAY['bar_liquor', 'duka', 'mini_supermarket'], ARRAY['dunhill', 'dunhill packet']),
  ('Rooster Single', 'Cigarettes', 'Rooster', 1, 'stick', 'unit', 'Other', ARRAY['bar_liquor', 'duka', 'mini_supermarket'], ARRAY['rooster', 'rooster single']),
  ('Rooster Packet', 'Cigarettes', 'Rooster', 20, 'stick', 'unit', 'Other', ARRAY['bar_liquor', 'duka', 'mini_supermarket'], ARRAY['rooster', 'rooster packet']),
  ('SuperMatch Single', 'Cigarettes', 'SuperMatch', 1, 'stick', 'unit', 'Other', ARRAY['bar_liquor', 'duka', 'mini_supermarket'], ARRAY['super match', 'supermatch', 'supermatch single']),
  ('SuperMatch Packet', 'Cigarettes', 'SuperMatch', 20, 'stick', 'unit', 'Other', ARRAY['bar_liquor', 'duka', 'mini_supermarket'], ARRAY['super match', 'supermatch', 'supermatch packet']),
  ('Safari Single', 'Cigarettes', 'Safari', 1, 'stick', 'unit', 'Other', ARRAY['bar_liquor', 'duka', 'mini_supermarket'], ARRAY['safari', 'safari single']),
  ('Safari Packet', 'Cigarettes', 'Safari', 20, 'stick', 'unit', 'Other', ARRAY['bar_liquor', 'duka', 'mini_supermarket'], ARRAY['safari', 'safari packet'])
ON CONFLICT (name) DO UPDATE
  SET product_type   = EXCLUDED.product_type,
      brand          = EXCLUDED.brand,
      size_value     = EXCLUDED.size_value,
      size_unit      = EXCLUDED.size_unit,
      sold_by        = EXCLUDED.sold_by,
      category       = EXCLUDED.category,
      business_types = EXCLUDED.business_types,
      aliases        = EXCLUDED.aliases;
